### ISSUE TITLE
Error in T10 Prey

### ISSUE THREAD

**Issue by Legends0** [quisquous/cactbot#1397]
```
[4/30/2020 6:48:35 PM] Info: cactbot: 0.17.2.0 C:\Program Files\Advanced Combat Tracker\OverlayPlugin-nlgd\cactbot\CactbotOverlay.dll (dir: C:\Program Files\Advanced Combat Tracker\OverlayPlugin-nlgd\cactbot)
[4/30/2020 6:48:35 PM] Info: OverlayPlugin: 0.14.1.0 C:\Program Files\Advanced Combat Tracker\OverlayPlugin-nlgd\OverlayPlugin.dll
[4/30/2020 6:48:35 PM] Info: FFXIV Plugin: 2.0.5.10 C:\Users\nac10\AppData\Roaming\Advanced Combat Tracker\Plugins\FFXIV_ACT_Plugin.dll
[4/30/2020 6:48:35 PM] Info: ACT: 3.4.7.268 C:\Program Files\Advanced Combat Tracker\Advanced Combat Tracker.exe
[4/30/2020 6:48:35 PM] Info: Language: en
[4/30/2020 6:48:35 PM] Info: Version: intl
```

Received this error in T10 today with 2 party members:

```
[4/30/2020 7:57:39 PM] Info: Cactbot: BrowserConsole: Error in trigger: T10 Prey (02-arr/raid/t10.js) (Source: file:///C:/Program%20Files/Advanced%20Combat%20Tracker/OverlayPlugin-nlgd/cactbot/ui/raidboss/popup-text.js, Line: 16)
[4/30/2020 7:57:39 PM] Info: Cactbot: BrowserConsole: ReferenceError: target is not defined (Source: file:///C:/Program%20Files/Advanced%20Combat%20Tracker/OverlayPlugin-nlgd/cactbot/ui/raidboss/popup-text.js, Line: 20)
[4/30/2020 7:57:39 PM] Info: Cactbot: BrowserConsole:     at otherFunc (file:///C:/Program%20Files/Advanced%20Combat%20Tracker/OverlayPlugin-nlgd/cactbot/resources/responses.js:715:43) (Source: file:///C:/Program%20Files/Advanced%20Combat%20Tracker/OverlayPlugin-nlgd/cactbot/ui/raidboss/popup-text.js, Line: 20)
[4/30/2020 7:57:39 PM] Info: Cactbot: BrowserConsole:     at ValueOrFunction (file:///C:/Program%20Files/Advanced%20Combat%20Tracker/OverlayPlugin-nlgd/cactbot/ui/raidboss/popup-text.js:395:48) (Source: file:///C:/Program%20Files/Advanced%20Combat%20Tracker/OverlayPlugin-nlgd/cactbot/ui/raidboss/popup-text.js, Line: 20)
[4/30/2020 7:57:39 PM] Info: Cactbot: BrowserConsole:     at f (file:///C:/Program%20Files/Advanced%20Combat%20Tracker/OverlayPlugin-nlgd/cactbot/ui/raidboss/popup-text.js:552:20) (Source: file:///C:/Program%20Files/Advanced%20Combat%20Tracker/OverlayPlugin-nlgd/cactbot/ui/raidboss/popup-text.js, Line: 20)
[4/30/2020 7:57:39 PM] Info: Cactbot: BrowserConsole:     at runTriggerBody (file:///C:/Program%20Files/Advanced%20Combat%20Tracker/OverlayPlugin-nlgd/cactbot/ui/raidboss/popup-text.js:689:11) (Source: file:///C:/Program%20Files/Advanced%20Combat%20Tracker/OverlayPlugin-nlgd/cactbot/ui/raidboss/popup-text.js, Line: 20)
[4/30/2020 7:57:39 PM] Info: Cactbot: BrowserConsole:     at promiseThenTrigger (file:///C:/Program%20Files/Advanced%20Combat%20Tracker/OverlayPlugin-nlgd/cactbot/ui/raidboss/popup-text.js:701:9) (Source: file:///C:/Program%20Files/Advanced%20Combat%20Tracker/OverlayPlugin-nlgd/cactbot/ui/raidboss/popup-text.js, Line: 20)
[4/30/2020 7:57:39 PM] Info: Cactbot: BrowserConsole:     at PopupText.OnTriggerInternal (file:///C:/Program%20Files/Advanced%20Combat%20Tracker/OverlayPlugin-nlgd/cactbot/ui/raidboss/popup-text.js:706:7) (Source: file:///C:/Program%20Files/Advanced%20Combat%20Tracker/OverlayPlugin-nlgd/cactbot/ui/raidboss/popup-text.js, Line: 20)
[4/30/2020 7:57:39 PM] Info: Cactbot: BrowserConsole:     at PopupText.OnTrigger (file:///C:/Program%20Files/Advanced%20Combat%20Tracker/OverlayPlugin-nlgd/cactbot/ui/raidboss/popup-text.js:357:12) (Source: file:///C:/Program%20Files/Advanced%20Combat%20Tracker/OverlayPlugin-nlgd/cactbot/ui/raidboss/popup-text.js, Line: 20)
[4/30/2020 7:57:39 PM] Info: Cactbot: BrowserConsole:     at PopupText.OnLog (file:///C:/Program%20Files/Advanced%20Combat%20Tracker/OverlayPlugin-nlgd/cactbot/ui/raidboss/popup-text.js:350:16) (Source: file:///C:/Program%20Files/Advanced%20Combat%20Tracker/OverlayPlugin-nlgd/cactbot/ui/raidboss/popup-text.js, Line: 20)
[4/30/2020 7:57:39 PM] Info: Cactbot: BrowserConsole:     at file:///C:/Program%20Files/Advanced%20Combat%20Tracker/OverlayPlugin-nlgd/cactbot/ui/raidboss/popup-text.js:70:12 (Source: file:///C:/Program%20Files/Advanced%20Combat%20Tracker/OverlayPlugin-nlgd/cactbot/ui/raidboss/popup-text.js, Line: 20)
[4/30/2020 7:57:39 PM] Info: Cactbot: BrowserConsole:     at processEvent (file:///C:/Program%20Files/Advanced%20Combat%20Tracker/OverlayPlugin-nlgd/cactbot/resources/common.js:236:9) (Source: file:///C:/Program%20Files/Advanced%20Combat%20Tracker/OverlayPlugin-nlgd/cactbot/ui/raidboss/popup-text.js, Line: 20)
[4/30/2020 7:58:14 PM] Info: Cactbot: BrowserConsole: Error in trigger: T10 Prey (02-arr/raid/t10.js) (Source: file:///C:/Program%20Files/Advanced%20Combat%20Tracker/OverlayPlugin-nlgd/cactbot/ui/raidboss/popup-text.js, Line: 16)
[4/30/2020 7:58:14 PM] Info: Cactbot: BrowserConsole: ReferenceError: target is not defined (Source: file:///C:/Program%20Files/Advanced%20Combat%20Tracker/OverlayPlugin-nlgd/cactbot/ui/raidboss/popup-text.js, Line: 20)
[4/30/2020 7:58:14 PM] Info: Cactbot: BrowserConsole:     at otherFunc (file:///C:/Program%20Files/Advanced%20Combat%20Tracker/OverlayPlugin-nlgd/cactbot/resources/responses.js:715:43) (Source: file:///C:/Program%20Files/Advanced%20Combat%20Tracker/OverlayPlugin-nlgd/cactbot/ui/raidboss/popup-text.js, Line: 20)
[4/30/2020 7:58:14 PM] Info: Cactbot: BrowserConsole:     at ValueOrFunction (file:///C:/Program%20Files/Advanced%20Combat%20Tracker/OverlayPlugin-nlgd/cactbot/ui/raidboss/popup-text.js:395:48) (Source: file:///C:/Program%20Files/Advanced%20Combat%20Tracker/OverlayPlugin-nlgd/cactbot/ui/raidboss/popup-text.js, Line: 20)
[4/30/2020 7:58:14 PM] Info: Cactbot: BrowserConsole:     at f (file:///C:/Program%20Files/Advanced%20Combat%20Tracker/OverlayPlugin-nlgd/cactbot/ui/raidboss/popup-text.js:552:20) (Source: file:///C:/Program%20Files/Advanced%20Combat%20Tracker/OverlayPlugin-nlgd/cactbot/ui/raidboss/popup-text.js, Line: 20)
[4/30/2020 7:58:14 PM] Info: Cactbot: BrowserConsole:     at runTriggerBody (file:///C:/Program%20Files/Advanced%20Combat%20Tracker/OverlayPlugin-nlgd/cactbot/ui/raidboss/popup-text.js:689:11) (Source: file:///C:/Program%20Files/Advanced%20Combat%20Tracker/OverlayPlugin-nlgd/cactbot/ui/raidboss/popup-text.js, Line: 20)
[4/30/2020 7:58:14 PM] Info: Cactbot: BrowserConsole:     at promiseThenTrigger (file:///C:/Program%20Files/Advanced%20Combat%20Tracker/OverlayPlugin-nlgd/cactbot/ui/raidboss/popup-text.js:701:9) (Source: file:///C:/Program%20Files/Advanced%20Combat%20Tracker/OverlayPlugin-nlgd/cactbot/ui/raidboss/popup-text.js, Line: 20)
[4/30/2020 7:58:14 PM] Info: Cactbot: BrowserConsole:     at PopupText.OnTriggerInternal (file:///C:/Program%20Files/Advanced%20Combat%20Tracker/OverlayPlugin-nlgd/cactbot/ui/raidboss/popup-text.js:706:7) (Source: file:///C:/Program%20Files/Advanced%20Combat%20Tracker/OverlayPlugin-nlgd/cactbot/ui/raidboss/popup-text.js, Line: 20)
[4/30/2020 7:58:14 PM] Info: Cactbot: BrowserConsole:     at PopupText.OnTrigger (file:///C:/Program%20Files/Advanced%20Combat%20Tracker/OverlayPlugin-nlgd/cactbot/ui/raidboss/popup-text.js:357:12) (Source: file:///C:/Program%20Files/Advanced%20Combat%20Tracker/OverlayPlugin-nlgd/cactbot/ui/raidboss/popup-text.js, Line: 20)
[4/30/2020 7:58:14 PM] Info: Cactbot: BrowserConsole:     at PopupText.OnLog (file:///C:/Program%20Files/Advanced%20Combat%20Tracker/OverlayPlugin-nlgd/cactbot/ui/raidboss/popup-text.js:350:16) (Source: file:///C:/Program%20Files/Advanced%20Combat%20Tracker/OverlayPlugin-nlgd/cactbot/ui/raidboss/popup-text.js, Line: 20)
[4/30/2020 7:58:14 PM] Info: Cactbot: BrowserConsole:     at file:///C:/Program%20Files/Advanced%20Combat%20Tracker/OverlayPlugin-nlgd/cactbot/ui/raidboss/popup-text.js:70:12 (Source: file:///C:/Program%20Files/Advanced%20Combat%20Tracker/OverlayPlugin-nlgd/cactbot/ui/raidboss/popup-text.js, Line: 20)
[4/30/2020 7:58:14 PM] Info: Cactbot: BrowserConsole:     at processEvent (file:///C:/Program%20Files/Advanced%20Combat%20Tracker/OverlayPlugin-nlgd/cactbot/resources/common.js:236:9) (Source: file:///C:/Program%20Files/Advanced%20Combat%20Tracker/OverlayPlugin-nlgd/cactbot/ui/raidboss/popup-text.js, Line: 20)

```

**Comment by quisquous** [comment]
Thanks.  I'll try to take a look at this, this weekend.  I don't seen anything wrong offhand, but it should be easy to sort out with some testing.

**Comment by VanSlanzar** [comment]
The last time, I redid t1 to t13, and there were 2 memory errors. t9 and t10.

[01/05/2020 17:05:27] Info: Raidboss Alerts: BrowserConsole: Error in trigger: T9 Final Phase Reset (02-arr/raid/t9.js) (Source: file:///C:/Users/Bauer/AppData/Roaming/Advanced%20Combat%20Tracker/Plugins/cactbot/ui/raidboss/popup-text.js, Line: 16)
[01/05/2020 17:05:27] Info: Raidboss Alerts: BrowserConsole: TypeError: Cannot read property 'sort' of undefined (Source: file:///C:/Users/Bauer/AppData/Roaming/Advanced%20Combat%20Tracker/Plugins/cactbot/ui/raidboss/popup-text.js, Line: 20)
[01/05/2020 17:05:27] Info: Raidboss Alerts: BrowserConsole:     at Object.run (eval at OnDataFilesRead (file:///C:/Users/Bauer/AppData/Roaming/Advanced%20Combat%20Tracker/Plugins/cactbot/ui/raidboss/popup-text.js:108:16), <anonymous>:292:36) (Source: file:///C:/Users/Bauer/AppData/Roaming/Advanced%20Combat%20Tracker/Plugins/cactbot/ui/raidboss/popup-text.js, Line: 20)
[01/05/2020 17:05:27] Info: Raidboss Alerts: BrowserConsole:     at f (file:///C:/Users/Bauer/AppData/Roaming/Advanced%20Combat%20Tracker/Plugins/cactbot/ui/raidboss/popup-text.js:667:17) (Source: file:///C:/Users/Bauer/AppData/Roaming/Advanced%20Combat%20Tracker/Plugins/cactbot/ui/raidboss/popup-text.js, Line: 20)
[01/05/2020 17:05:27] Info: Raidboss Alerts: BrowserConsole:     at runTriggerBody (file:///C:/Users/Bauer/AppData/Roaming/Advanced%20Combat%20Tracker/Plugins/cactbot/ui/raidboss/popup-text.js:689:11) (Source: file:///C:/Users/Bauer/AppData/Roaming/Advanced%20Combat%20Tracker/Plugins/cactbot/ui/raidboss/popup-text.js, Line: 20)
[01/05/2020 17:05:27] Info: Raidboss Alerts: BrowserConsole:     at promiseThenTrigger (file:///C:/Users/Bauer/AppData/Roaming/Advanced%20Combat%20Tracker/Plugins/cactbot/ui/raidboss/popup-text.js:701:9) (Source: file:///C:/Users/Bauer/AppData/Roaming/Advanced%20Combat%20Tracker/Plugins/cactbot/ui/raidboss/popup-text.js, Line: 20)
[01/05/2020 17:05:27] Info: Raidboss Alerts: BrowserConsole:     at PopupText.OnTriggerInternal (file:///C:/Users/Bauer/AppData/Roaming/Advanced%20Combat%20Tracker/Plugins/cactbot/ui/raidboss/popup-text.js:706:7) (Source: file:///C:/Users/Bauer/AppData/Roaming/Advanced%20Combat%20Tracker/Plugins/cactbot/ui/raidboss/popup-text.js, Line: 20)
[01/05/2020 17:05:27] Info: Raidboss Alerts: BrowserConsole:     at PopupText.OnTrigger (file:///C:/Users/Bauer/AppData/Roaming/Advanced%20Combat%20Tracker/Plugins/cactbot/ui/raidboss/popup-text.js:357:12) (Source: file:///C:/Users/Bauer/AppData/Roaming/Advanced%20Combat%20Tracker/Plugins/cactbot/ui/raidboss/popup-text.js, Line: 20)
[01/05/2020 17:05:27] Info: Raidboss Alerts: BrowserConsole:     at PopupText.OnLog (file:///C:/Users/Bauer/AppData/Roaming/Advanced%20Combat%20Tracker/Plugins/cactbot/ui/raidboss/popup-text.js:350:16) (Source: file:///C:/Users/Bauer/AppData/Roaming/Advanced%20Combat%20Tracker/Plugins/cactbot/ui/raidboss/popup-text.js, Line: 20)
[01/05/2020 17:05:27] Info: Raidboss Alerts: BrowserConsole:     at file:///C:/Users/Bauer/AppData/Roaming/Advanced%20Combat%20Tracker/Plugins/cactbot/ui/raidboss/popup-text.js:70:12 (Source: file:///C:/Users/Bauer/AppData/Roaming/Advanced%20Combat%20Tracker/Plugins/cactbot/ui/raidboss/popup-text.js, Line: 20)
[01/05/2020 17:05:27] Info: Raidboss Alerts: BrowserConsole:     at processEvent (file:///C:/Users/Bauer/AppData/Roaming/Advanced%20Combat%20Tracker/Plugins/cactbot/resources/common.js:236:9) (Source: file:///C:/Users/Bauer/AppData/Roaming/Advanced%20Combat%20Tracker/Plugins/cactbot/ui/raidboss/popup-text.js, Line: 20)
[01/05/2020 17:05:27] Info: Raidboss Alerts: BrowserConsole:     at <anonymous>:1:30 (Source: file:///C:/Users/Bauer/AppData/Roaming/Advanced%20Combat%20Tracker/Plugins/cactbot/ui/raidboss/popup-text.js, Line: 20)
[01/05/2020 17:05:27] Info: Raidboss Alerts: BrowserConsole: Error in trigger: T9 Dragon Marks (02-arr/raid/t9.js) (Source: file:///C:/Users/Bauer/AppData/Roaming/Advanced%20Combat%20Tracker/Plugins/cactbot/ui/raidboss/popup-text.js, Line: 16)
[01/05/2020 17:05:27] Info: Raidboss Alerts: BrowserConsole: TypeError: Cannot read property 'join' of undefined (Source: file:///C:/Users/Bauer/AppData/Roaming/Advanced%20Combat%20Tracker/Plugins/cactbot/ui/raidboss/popup-text.js, Line: 20)
[01/05/2020 17:05:27] Info: Raidboss Alerts: BrowserConsole:     at infoText (eval at OnDataFilesRead (file:///C:/Users/Bauer/AppData/Roaming/Advanced%20Combat%20Tracker/Plugins/cactbot/ui/raidboss/popup-text.js:108:16), <anonymous>:318:42) (Source: file:///C:/Users/Bauer/AppData/Roaming/Advanced%20Combat%20Tracker/Plugins/cactbot/ui/raidboss/popup-text.js, Line: 20)
[01/05/2020 17:05:27] Info: Raidboss Alerts: BrowserConsole:     at ValueOrFunction (file:///C:/Users/Bauer/AppData/Roaming/Advanced%20Combat%20Tracker/Plugins/cactbot/ui/raidboss/popup-text.js:395:48) (Source: file:///C:/Users/Bauer/AppData/Roaming/Advanced%20Combat%20Tracker/Plugins/cactbot/ui/raidboss/popup-text.js, Line: 20)
[01/05/2020 17:05:27] Info: Raidboss Alerts: BrowserConsole:     at f (file:///C:/Users/Bauer/AppData/Roaming/Advanced%20Combat%20Tracker/Plugins/cactbot/ui/raidboss/popup-text.js:552:20) (Source: file:///C:/Users/Bauer/AppData/Roaming/Advanced%20Combat%20Tracker/Plugins/cactbot/ui/raidboss/popup-text.js, Line: 20)
[01/05/2020 17:05:27] Info: Raidboss Alerts: BrowserConsole:     at runTriggerBody (file:///C:/Users/Bauer/AppData/Roaming/Advanced%20Combat%20Tracker/Plugins/cactbot/ui/raidboss/popup-text.js:689:11) (Source: file:///C:/Users/Bauer/AppData/Roaming/Advanced%20Combat%20Tracker/Plugins/cactbot/ui/raidboss/popup-text.js, Line: 20)
[01/05/2020 17:05:27] Info: Raidboss Alerts: BrowserConsole:     at promiseThenTrigger (file:///C:/Users/Bauer/AppData/Roaming/Advanced%20Combat%20Tracker/Plugins/cactbot/ui/raidboss/popup-text.js:701:9) (Source: file:///C:/Users/Bauer/AppData/Roaming/Advanced%20Combat%20Tracker/Plugins/cactbot/ui/raidboss/popup-text.js, Line: 20)
[01/05/2020 17:05:27] Info: Raidboss Alerts: BrowserConsole:     at PopupText.OnTriggerInternal (file:///C:/Users/Bauer/AppData/Roaming/Advanced%20Combat%20Tracker/Plugins/cactbot/ui/raidboss/popup-text.js:706:7) (Source: file:///C:/Users/Bauer/AppData/Roaming/Advanced%20Combat%20Tracker/Plugins/cactbot/ui/raidboss/popup-text.js, Line: 20)
[01/05/2020 17:05:27] Info: Raidboss Alerts: BrowserConsole:     at PopupText.OnTrigger (file:///C:/Users/Bauer/AppData/Roaming/Advanced%20Combat%20Tracker/Plugins/cactbot/ui/raidboss/popup-text.js:357:12) (Source: file:///C:/Users/Bauer/AppData/Roaming/Advanced%20Combat%20Tracker/Plugins/cactbot/ui/raidboss/popup-text.js, Line: 20)
[01/05/2020 17:05:27] Info: Raidboss Alerts: BrowserConsole:     at PopupText.OnLog (file:///C:/Users/Bauer/AppData/Roaming/Advanced%20Combat%20Tracker/Plugins/cactbot/ui/raidboss/popup-text.js:350:16) (Source: file:///C:/Users/Bauer/AppData/Roaming/Advanced%20Combat%20Tracker/Plugins/cactbot/ui/raidboss/popup-text.js, Line: 20)
[01/05/2020 17:05:27] Info: Raidboss Alerts: BrowserConsole:     at file:///C:/Users/Bauer/AppData/Roaming/Advanced%20Combat%20Tracker/Plugins/cactbot/ui/raidboss/popup-text.js:70:12 (Source: file:///C:/Users/Bauer/AppData/Roaming/Advanced%20Combat%20Tracker/Plugins/cactbot/ui/raidboss/popup-text.js, Line: 20)
[01/05/2020 17:05:27] Info: Raidboss Alerts: BrowserConsole:     at processEvent (file:///C:/Users/Bauer/AppData/Roaming/Advanced%20Combat%20Tracker/Plugins/cactbot/resources/common.js:236:9) (Source: file:///C:/Users/Bauer/AppData/Roaming/Advanced%20Combat%20Tracker/Plugins/cactbot/ui/raidboss/popup-text.js, Line: 20)

**Comment by quisquous** [comment]
@Legends0  t10 worked just fine for me.  Can you attach a network log for me here?

@VanSlanzar Can you attach a log for t9 where this didn't work?

**Comment by Legends0** [comment]
Network log of T10.
[Network_20510_20200430.2020.05.01-split-2020-04-30T23-53-00.159Z.log](https://github.com/quisquous/cactbot/files/4567329/Network_20510_20200430.2020.05.01-split-2020-04-30T23-53-00.159Z.log)

I did not run into the bug in T9 that VanSlanzar mentions.

**Comment by VanSlanzar** [comment]
[T9.zip](https://github.com/quisquous/cactbot/files/4570945/T9.zip)

**Comment by quisquous** [comment]
Ok, I see what's wrong with t9.  There's incorrect capitalization inside of the function itself.  I think I can fix it.  Unfortunately, it's tough to know if I fixed it properly with just an ".act" file.  Sorry for not giving better directions.

I wrote this for how to find network logs, if you need to send one in the future: https://github.com/quisquous/cactbot/blob/master/docs/FAQ-Troubleshooting.md#how-to-find-a-network-log

**Comment by VanSlanzar** [comment]
Thank you for your work.
