### ISSUE TITLE
Parser DPS json serializer exception

### ISSUE THREAD

**Issue by quisquous** [quisquous/cactbot#14]
10/14/2017 10:57:15 AM: Error: XepheroDPS: Exception in SendFastRateEvents: Can not add property Jenn Taeem to Newtonsoft.Json.Linq.JObject. Property with the same name already exists on object.
10/14/2017 10:57:15 AM: Error: XepheroDPS: Stack:    at Newtonsoft.Json.Linq.JObject.ValidateToken(JToken o, JToken existing)
   at Newtonsoft.Json.Linq.JContainer.InsertItem(Int32 index, JToken item, Boolean skipParentCheck)
   at Newtonsoft.Json.Linq.JContainer.AddInternal(Int32 index, Object content, Boolean skipParentCheck)
   at Cactbot.JSEvents.DPSDetail.CombatantConverter.WriteJson(JsonWriter writer, Object value, JsonSerializer serializer)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeConvertable(JsonWriter writer, JsonConverter converter, Object value, JsonContract contract, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.Linq.JToken.FromObjectInternal(Object o, JsonSerializer jsonSerializer)
   at Newtonsoft.Json.Linq.JObject.FromObject(Object o, JsonSerializer jsonSerializer)
   at Cactbot.JSEvents.DPSOverlayUpdateEvent.DPSOverlayUpdateEventConverter.WriteJson(JsonWriter writer, Object value, JsonSerializer serializer)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeConvertable(JsonWriter writer, JsonConverter converter, Object value, JsonContract contract, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Object value, Type objectType)
   at Cactbot.CactbotOverlay.DispatchToJS(JSEvent e)
   at Cactbot.FightTracker.Tick(DateTime time)
   at Cactbot.CactbotOverlay.SendFastRateEvents()
   at Cactbot.CactbotOverlay.<.ctor>b__74_0(Object o, ElapsedEventArgs args)
10/14/2017 10:57:15 AM: Error: XepheroDPS: Source: Newtonsoft.Json

**Comment by quisquous** [comment]
I haven't seen this in months.
