### ISSUE TITLE
Custom triggers not working since 0.18.0

### ISSUE THREAD

**Issue by KarlitosVII** [quisquous/cactbot#1537]
Hello, since 0.18.0 some of my custom triggers are no longer working.

```javascript
Options.Triggers = [
// General
{
    zoneRegex: /./,
    triggers: [
    // AFK Alert
    {
        regex: Regexes.gameLog({ line: 'Votre personnage est inactif depuis [0-9]+ minutes\. Il sera expulsé de cette instance', capture: false }),
        alarmText: 'STOP AFK',
        durationSeconds: 10,
        sound: '../../../Karlitos/hoodwolftransformplayer01.wav',
    },
    // Khloe
    {
        regex: Regexes.gameLog({ line: 'Vous avez réussi une aventure du carnet de Khloe', capture: false }),
        infoText: 'Carnet de Khloe',
        durationSeconds: 10,
        sound: '../../resources/sounds/Overwatch/D.Va_-_Game_on.ogg',
    },
},
];
```

If I use bare regexes instead of "Regexes.gameLog" this gave me a weird error: "Failed to set the ‘volume’ property on ‘HTMLMediaElement’: The provided double value is non-finite"

**Comment by quisquous** [comment]
Ah, sorry.  I should have mentioned this in the release notes more clearly.  I changed this to match up with other log types (and because it would have been confusing for the `NetRegexes.gameLog` version.  `gameLog` only matches the whole line now, so you need a `.*` at the end of it.

Use these instead:
* ` regex: Regexes.gameLog({ line: 'Votre personnage est inactif depuis [0-9]+ minutes\. Il sera expulsé de cette instance.*', capture: false }),`
* `regex: Regexes.gameLog({ line: 'Vous avez réussi une aventure du carnet de Khloe.*', capture: false }),`

**Comment by KarlitosVII** [comment]
Ah ok, thanks. :)

**Comment by KarlitosVII** [comment]
Now it works but with no sound

```
[02/07/2020 20:05:14] Info: Bossmod: BrowserConsole: Error in trigger: [unknown trigger id] (Source: file:///H:/Jeux/FINAL%20FANTASY%20XIV%20-%20A%20Realm%20Reborn/Karlitos/ACTv3/Plugins/cactbot/ui/raidboss/popup-text.js, Line: 18)
[02/07/2020 20:05:14] Info: Bossmod: BrowserConsole: TypeError: Failed to set the 'volume' property on 'HTMLMediaElement': The provided double value is non-finite. (Source: file:///H:/Jeux/FINAL%20FANTASY%20XIV%20-%20A%20Realm%20Reborn/Karlitos/ACTv3/Plugins/cactbot/ui/raidboss/popup-text.js, Line: 22)
[02/07/2020 20:05:14] Info: Bossmod: BrowserConsole:     at PopupText._playAudioFile (file:///H:/Jeux/FINAL%20FANTASY%20XIV%20-%20A%20Realm%20Reborn/Karlitos/ACTv3/Plugins/cactbot/ui/raidboss/popup-text.js:800:18) (Source: file:///H:/Jeux/FINAL%20FANTASY%20XIV%20-%20A%20Realm%20Reborn/Karlitos/ACTv3/Plugins/cactbot/ui/raidboss/popup-text.js, Line: 22)
[02/07/2020 20:05:14] Info: Bossmod: BrowserConsole:     at PopupText._onTriggerInternalPlayAudio (file:///H:/Jeux/FINAL%20FANTASY%20XIV%20-%20A%20Realm%20Reborn/Karlitos/ACTv3/Plugins/cactbot/ui/raidboss/popup-text.js:733:12) (Source: file:///H:/Jeux/FINAL%20FANTASY%20XIV%20-%20A%20Realm%20Reborn/Karlitos/ACTv3/Plugins/cactbot/ui/raidboss/popup-text.js, Line: 22)
[02/07/2020 20:05:14] Info: Bossmod: BrowserConsole:     at triggerPostPromise (file:///H:/Jeux/FINAL%20FANTASY%20XIV%20-%20A%20Realm%20Reborn/Karlitos/ACTv3/Plugins/cactbot/ui/raidboss/popup-text.js:454:14) (Source: file:///H:/Jeux/FINAL%20FANTASY%20XIV%20-%20A%20Realm%20Reborn/Karlitos/ACTv3/Plugins/cactbot/ui/raidboss/popup-text.js, Line: 22)
[02/07/2020 20:05:14] Info: Bossmod: BrowserConsole:     at triggerPostDelay (file:///H:/Jeux/FINAL%20FANTASY%20XIV%20-%20A%20Realm%20Reborn/Karlitos/ACTv3/Plugins/cactbot/ui/raidboss/popup-text.js:462:9) (Source: file:///H:/Jeux/FINAL%20FANTASY%20XIV%20-%20A%20Realm%20Reborn/Karlitos/ACTv3/Plugins/cactbot/ui/raidboss/popup-text.js, Line: 22)
[02/07/2020 20:05:14] Info: Bossmod: BrowserConsole:     at PopupText.OnTriggerInternal (file:///H:/Jeux/FINAL%20FANTASY%20XIV%20-%20A%20Realm%20Reborn/Karlitos/ACTv3/Plugins/cactbot/ui/raidboss/popup-text.js:469:7) (Source: file:///H:/Jeux/FINAL%20FANTASY%20XIV%20-%20A%20Realm%20Reborn/Karlitos/ACTv3/Plugins/cactbot/ui/raidboss/popup-text.js, Line: 22)
[02/07/2020 20:05:14] Info: Bossmod: BrowserConsole:     at PopupText.OnTrigger (file:///H:/Jeux/FINAL%20FANTASY%20XIV%20-%20A%20Realm%20Reborn/Karlitos/ACTv3/Plugins/cactbot/ui/raidboss/popup-text.js:388:12) (Source: file:///H:/Jeux/FINAL%20FANTASY%20XIV%20-%20A%20Realm%20Reborn/Karlitos/ACTv3/Plugins/cactbot/ui/raidboss/popup-text.js, Line: 22)
[02/07/2020 20:05:14] Info: Bossmod: BrowserConsole:     at PopupText.OnLog (file:///H:/Jeux/FINAL%20FANTASY%20XIV%20-%20A%20Realm%20Reborn/Karlitos/ACTv3/Plugins/cactbot/ui/raidboss/popup-text.js:372:16) (Source: file:///H:/Jeux/FINAL%20FANTASY%20XIV%20-%20A%20Realm%20Reborn/Karlitos/ACTv3/Plugins/cactbot/ui/raidboss/popup-text.js, Line: 22)
[02/07/2020 20:05:14] Info: Bossmod: BrowserConsole:     at file:///H:/Jeux/FINAL%20FANTASY%20XIV%20-%20A%20Realm%20Reborn/Karlitos/ACTv3/Plugins/cactbot/ui/raidboss/popup-text.js:77:12 (Source: file:///H:/Jeux/FINAL%20FANTASY%20XIV%20-%20A%20Realm%20Reborn/Karlitos/ACTv3/Plugins/cactbot/ui/raidboss/popup-text.js, Line: 22)
[02/07/2020 20:05:14] Info: Bossmod: BrowserConsole:     at processEvent (file:///H:/Jeux/FINAL%20FANTASY%20XIV%20-%20A%20Realm%20Reborn/Karlitos/ACTv3/Plugins/cactbot/resources/common.js:239:9) (Source: file:///H:/Jeux/FINAL%20FANTASY%20XIV%20-%20A%20Realm%20Reborn/Karlitos/ACTv3/Plugins/cactbot/ui/raidboss/popup-text.js, Line: 22)
[02/07/2020 20:05:14] Info: Bossmod: BrowserConsole:     at <anonymous>:1:30 (Source: file:///H:/Jeux/FINAL%20FANTASY%20XIV%20-%20A%20Realm%20Reborn/Karlitos/ACTv3/Plugins/cactbot/ui/raidboss/popup-text.js, Line: 22)
```

**Comment by quisquous** [comment]
Huh.  When did this start happening?

If you add the line `console.log('volume: ' + volume);` immediately after `_playAudioFile(url, volume) {` in `ui/raidboss/popup-text.js` and reload raidboss, what does it print out?

**Comment by KarlitosVII** [comment]
Yep 0.18.0

```
[02/07/2020 23:31:42] Info: Bossmod: BrowserConsole: volume: undefined (Source: file:///H:/Jeux/FINAL%20FANTASY%20XIV%20-%20A%20Realm%20Reborn/Karlitos/ACTv3/Plugins/cactbot/ui/raidboss/popup-text.js, Line: 799)
```

Then the same error as before.

**Comment by quisquous** [comment]
Ah ok, I think I see what the issue is, thanks.  I'll try to get a fix in later today.

**Comment by quisquous** [comment]
Ok, c0198e0 should fix it.  Your options are:
* add `soundVolume: 1` to all of your triggers, which will work around the problem
* copy that change I made into your local version for now until the next release
* use https://quisquous.github.io/cactbot/ui/raidboss/raidboss.html as your raidboss url to use the latest version which includes this fix
