### ISSUE TITLE
Not appearing in Overlay.dll

### ISSUE THREAD

**Issue by topofdarange** [quisquous/cactbot#1540]
Hi everyone,

I tried looking for youtube videos first and googling but cant seem to find people with this issue. I installed Cactbot using act and it is in my Plugin Listing tab and active so thats no issue. My problem is in the Overlayplugin.dll tab when I press New and go to the dropdown menu I dont see any Cactbot options. I even tried to copy/paste the cactbotoverlay.dll into the addons folder in the Overlay folderlike I saw online and then change the plugin in the Plugin Listings tab just to see and still not 1 Cactbot option. 

Can anyone help me and tell me where I went wrong if I went wrong? 

Thanks :)

**Comment by JLGarber** [comment]
The options no longer show up as Cactbot overlay types directly. Instead, you need to select Miniparse as the type of overlay. Then, in the URL field, put the file location for the raidboss.html file that you would normally use. From there, the configuration should work as you expect.

**Comment by quisquous** [comment]
You should not put cactbot in the addons folder any more.

Do [these steps](https://github.com/quisquous/cactbot#adding-overlay-modules) work for you?

**Comment by topofdarange** [comment]
> The options no longer show up as Cactbot overlay types directly. Instead, you need to select Miniparse as the type of overlay. Then, in the URL field, put the file location for the raidboss.html file that you would normally use. From there, the configuration should work as you expect.

I tried that and it worked thanks but I dont see how to change any option that way.

> You should not put cactbot in the addons folder any more.

Do these steps work for you?

I tried the start of it originally and it doesnt work. It installs fine and is in my Plugin Listings without any problems but in the OvwerlayPlugin.dll tab it has this error at the bottom and the options dont appear in the dropdown when I pick new.

[07/07/2020 19:48:16] Info: InitPlugin: PluginDirectory = C:\Users\%%%\AppData\Roaming\Advanced Combat Tracker\Plugins\OverlayPlugin
[07/07/2020 19:48:16] Info: InitPlugin: Initialized.
[07/07/2020 19:48:18] Error: LoadAddons: CactbotOverlay.dll: System.InvalidCastException: Unable to cast object of type 'Cactbot.PluginLoader' to type 'RainbowMage.OverlayPlugin.IOverlayAddonV2'.
   at RainbowMage.OverlayPlugin.PluginMain.LoadAddons()
[07/07/2020 19:54:57] Error: Got a subscription for missing event "onUserFileChanged"!
[07/07/2020 19:54:57] Error: Got a subscription for missing event "onForceReload"!
[07/07/2020 19:54:57] Error: JS Handler call failed: System.Exception: Tried to call missing handler "cactbotLoadData"!
   at RainbowMage.OverlayPlugin.EventDispatcher.CallHandler(JObject e)
   at RainbowMage.OverlayPlugin.EventDispatcher.ProcessHandlerMessage(IEventReceiver receiver, String data)
[07/07/2020 19:54:57] Error: JS Handler call failed: System.Exception: Tried to call missing handler "cactbotLoadUser"!
   at RainbowMage.OverlayPlugin.EventDispatcher.CallHandler(JObject e)
   at RainbowMage.OverlayPlugin.EventDispatcher.ProcessHandlerMessage(IEventReceiver receiver, String data)
[07/07/2020 19:54:57] Info: Cactbot Raidboss: BrowserConsole: Uncaught (in promise) TypeError: Cannot read property 'detail' of null (Source: file:///C:/Users/%%%/AppData/Roaming/Advanced%20Combat%20Tracker/Plugins/cactbot-0.18.0/cactbot/resources/user_config.js, Line: 35)

I dont know why its having this issue but would be great if you can help me fix it.

Thanks :)

**Comment by quisquous** [comment]
Glad you got it sorted.  I think the issue was likely that you had cactbot listed before overlayplugin.
