### ISSUE TITLE
fishing issue

### ISSUE THREAD

**Issue by ron2453** [quisquous/cactbot#1765]
first: i play in german, in english this issue dont exist
if i have mooch and catch fishes with double hook at the next cast the parse dont turn back to previous window so i have to hook for coming back. with normal hook it works fine.i think there is an error because language. so i found this line in the fisher.js probably has to be changed:
'catch': /00:0843:Du hast (?:einen |eine )?.+?\s?([\w\s-'.\d\u00c4-\u00fc]{3,})(?: | [^\w] |[^\w\s-'\u00c4-\u00fc].+ )(\d/,
in my game chat is written this way for 2 fishes:
"Du ziehst 2  Genist-Blindmantas  mit einer Länge von 272,6 Ilmen an Land!"
for one it looks like
Du hast einen  Genist-Wolkenspalter (21,8 Ilme) gefangen.
hope you can help to improve your nice work :)

**Comment by quisquous** [comment]
@Akurosia, do you have any time to look into this?

**Comment by Akurosia** [comment]
Might take a day or two, but should be no problem to check this :)

**Comment by Akurosia** [comment]
`0843:Du (hast (?:einen |eine )|ziehst \d+ )?.+?\s?([\w\s\-\'\.\d\u00c4-\u00fc]{3,})(?: | [^\w] |[^\w\s\-\'\u00c4-\u00fc].+ )(?:\(\d|mit)`

i checked some of my logs, and the above regex should work.
will take some time till i am able to test this, as i am currently deep into ishgard right now :x

**Comment by ron2453** [comment]
failed to look up fish: hast eine 
3seabase.js:222 
i think, i have to wait cause in diadem for now its useless without the new fishes... so waiting for your updates :)
but thanks for watching into it

**Comment by Akurosia** [comment]
ohh no apparently i am a dumb dumb...
i forgot to remove the new capture group in the beginning.
Could you try following? @ron2453 

`0843:Du (?:hast (?:einen |eine )|ziehst \d+ )?.+?\s?([\w\s\-\'\.\d\u00c4-\u00fc]{3,})(?: | [^\w] |[^\w\s\-\'\u00c4-\u00fc].+ )(?:\(\d|mit)`

**Comment by ron2453** [comment]
thats it! :) now just waiting for new fishes, awesome 👍

**Comment by ron2453** [comment]
nope.... if using mooch says this:

﻿
seabase.js:222 failed to look up fish: annst
5
seabase.js:267 Uncaught (in promise) DOMException: Failed to execute 'only' on 'IDBKeyRange': The parameter is not a valid key.
    at file:///C:/Users/ich/AppData/Roaming/Advanced%20Combat%20Tracker/Plugins/cactbot-0.19.6/cactbot/ui/fisher/seabase.js:267:36
    at new Promise (<anonymous>)
    at SeaBase.queryHookTimes (file:///C:/Users/ich/AppData/Roaming/Advanced%20Combat%20Tracker/Plugins/cactbot-0.19.6/cactbot/ui/fisher/seabase.js:266:12)
    at file:///C:/Users/ich/AppData/Roaming/Advanced%20Combat%20Tracker/Plugins/cactbot-0.19.6/cactbot/ui/fisher/seabase.js:299:15
seabase.js:222 failed to look up fish: annst
5
seabase.js:267 Uncaught (in promise) DOMException: Failed to execute 'only' on 'IDBKeyRange': The parameter is not a valid key.
    at file:///C:/Users/ich/AppData/Roaming/Advanced%20Combat%20Tracker/Plugins/cactbot-0.19.6/cactbot/ui/fisher/seabase.js:267:36
    at new Promise (<anonymous>)
    at SeaBase.queryHookTimes (file:///C:/Users/ich/AppData/Roaming/Advanced%20Combat%20Tracker/Plugins/cactbot-0.19.6/cactbot/ui/fisher/seabase.js:266:12)
    at file:///C:/Users/ich/AppData/Roaming/Advanced%20Combat%20Tracker/Plugins/cactbot-0.19.6/cactbot/ui/fisher/seabase.js:299:15
﻿
​

**Comment by Akurosia** [comment]
ok i just spend some minutes on fishing and u get slightly different results:

mooch 2 was working fine on 3-4 occasions but the only time i got mooch 1, it threw following issue:
```
[11.09.2020 23:35:41] Info: fischer: BrowserConsole: failed to look up fish: annst (Source: file:///E:/FINAL%20FANTASY%20XIV%20-%20A%20Realm%20Reborn/AdditionalExtern/ACT/Plugins/OverlayPlugin_ngld/cactbot/ui/fisher/seabase.js, Line: 222)
[11.09.2020 23:35:43] Info: fischer: BrowserConsole: Uncaught (in promise) DataError: Failed to execute 'only' on 'IDBKeyRange': The parameter is not a valid key. (Source: file:///E:/FINAL%20FANTASY%20XIV%20-%20A%20Realm%20Reborn/AdditionalExtern/ACT/Plugins/OverlayPlugin_ngld/cactbot/ui/fisher/seabase.js, Line: 267)
[11.09.2020 23:35:43] Info: fischer: BrowserConsole: Uncaught (in promise) DataError: Failed to execute 'only' on 'IDBKeyRange': The parameter is not a valid key. (Source: file:///E:/FINAL%20FANTASY%20XIV%20-%20A%20Realm%20Reborn/AdditionalExtern/ACT/Plugins/OverlayPlugin_ngld/cactbot/ui/fisher/seabase.js, Line: 267)
[11.09.2020 23:35:43] Info: fischer: BrowserConsole: Uncaught (in promise) DataError: Failed to execute 'only' on 'IDBKeyRange': The parameter is not a valid key. (Source: file:///E:/FINAL%20FANTASY%20XIV%20-%20A%20Realm%20Reborn/AdditionalExtern/ACT/Plugins/OverlayPlugin_ngld/cactbot/ui/fisher/seabase.js, Line: 267)
[11.09.2020 23:35:43] Info: fischer: BrowserConsole: Uncaught (in promise) DataError: Failed to execute 'only' on 'IDBKeyRange': The parameter is not a valid key. (Source: file:///E:/FINAL%20FANTASY%20XIV%20-%20A%20Realm%20Reborn/AdditionalExtern/ACT/Plugins/OverlayPlugin_ngld/cactbot/ui/fisher/seabase.js, Line: 267)
[11.09.2020 23:35:43] Info: fischer: BrowserConsole: Uncaught (in promise) DataError: Failed to execute 'only' on 'IDBKeyRange': The parameter is not a valid key. (Source: file:///E:/FINAL%20FANTASY%20XIV%20-%20A%20Realm%20Reborn/AdditionalExtern/ACT/Plugins/OverlayPlugin_ngld/cactbot/ui/fisher/seabase.js, Line: 267)
```

i will try it with following regex: `0843\|\|Du (?:hast (?:einen |eine )|ziehst \d+ )?.+?\s?([\w\s\-\'\.\d\u00c4-\u00fc]{3,})(?: | [^\w] |[^\w\s\-\'\u00c4-\u00fc].+ )(?:\(\d|mit ein)` as this does not match as much log lines as the other before

**Comment by ron2453** [comment]
2fisher.js:204 Uncaught TypeError: Cannot read property 'name' of null
    at Fisher.handleBait (fisher.js:204)
    at Fisher.handleMooch (fisher.js:293)
    at Fisher.parseLine (fisher.js:348)
    at Array.forEach (<anonymous>)
    at Fisher.OnLogEvent (fisher.js:362)
    at fisher.js:387
    at processEvent (common.js:241)
    at <anonymous>:1:30

and timer with mooch dont start... 
i have made some changes in static data for the new fishes (changed the old diadem to the new ones) so for now with the old code in fisher.js it works. i think we should work better this way: first finishing ishgard event, then inserting the new fishes and in the end turning to this problem, so we have booth exact the same files for working with :)

**Comment by Akurosia** [comment]
with the new regex i was able to mooch without problems.
if your static_data.js has not all entries, this could cause your issues. you could either clone the repository and run the gen_fish python tool, or use the version from my PR: https://github.com/quisquous/cactbot/pull/1785/files#diff-05f5a5ab84432d8ed1c9504da130a440

**Comment by ron2453** [comment]
ok, this last round wa yours!!  Its working fine now, great!
since i dont know how python works i have copied all the lines from your link above, static and fisher.
after this cross testing all cases, at least deleted my db for checking if entries are written and yes all fine without any error in console. 2 and 3 pieces per bait and mooch, also il return after double hook and moch works now, great job done :)
thanks a lot!

**Comment by ron2453** [comment]
found just an missing: "ein" in the line :D german is very complex. so its now:

        'catch': /00:0843:Du (?:hast (?:einen |eine |ein )|ziehst \d+ )?.+?\s?([\w\s\-\'\.\d\u00c4-\u00fc]{3,})(?: | [^\w] |[^\w\s\-\'\u00c4-\u00fc].+ )(?:\(\d|mit ein)/,

**Comment by Akurosia** [comment]
is this really needed?
do you have a example log line where it starts with "Du hast ein" ? I always encountered the "Du hast einen" version

**Comment by Akurosia** [comment]
ok nvm run a quick check through all my logs and found at least 1 occurence with the word "ein" `|0843||Du hast ein  Flieger-Ei (4,4 Ilme) gefangen.`
Will make a PR in a sec

**Comment by ron2453** [comment]
found also missing changes in static data since fishes in diadem has changed with 5.31
have changed this 4 lokations manually:
    '2262': [
      31590,
      31591,
      31592,
      31596,
      31600,
    ],
    '2263': [
      31590,
      31591,
      31593,
      31597,
      31602,
    ],
    '2264': [
      31590,
      31591,
      31594,
      31598,
      31601,

    '3489': [
      31590,
      31591,
      31595,
      31599,
      31603,
    ],

**Comment by Akurosia** [comment]
i made following PR #1787 to fix the regex
For the locations i ran a specialised python script. I honestly do not have time to invest this in detail (as i am not that familar with the data itself). @quisquous could you have a look at the location thing?

**Comment by quisquous** [comment]
Is there anything left here, or can this be closed?

**Comment by Akurosia** [comment]
could you have a look at the ids that were posted above?
The tool generated different once (`'2262': [30002,30003,30004,30006,30010,],` were created by the tool instead of what ron posted above).
I am not into the script or neither the static-data.js to be sure nothing is missing/incorrect

**Comment by quisquous** [comment]
I fixed the script to combine fish from all locations with the same id, so this should be better now.
