### ISSUE TITLE
riadboss ui not working

### ISSUE THREAD

**Issue by jenkshi** [quisquous/cactbot#1768]
[07/09/2020 01:23:01] Info: InitPlugin: PluginDirectory = C:\Users\Admin\AppData\Roaming\Advanced Combat Tracker\Plugins\OverlayPlugin
[07/09/2020 01:23:02] Info: InitPlugin: Initialized.
[07/09/2020 01:23:07] Error: JS Handler call failed: System.Exception: Tried to call missing handler "cactbotLoadData"!
   at RainbowMage.OverlayPlugin.EventDispatcher.CallHandler(JObject e)
   at RainbowMage.OverlayPlugin.EventDispatcher.ProcessHandlerMessage(IEventReceiver receiver, String data)
[07/09/2020 01:23:07] Error: JS Handler call failed: System.Exception: Tried to call missing handler "cactbotLoadUser"!
   at RainbowMage.OverlayPlugin.EventDispatcher.CallHandler(JObject e)
   at RainbowMage.OverlayPlugin.EventDispatcher.ProcessHandlerMessage(IEventReceiver receiver, String data)
[07/09/2020 01:23:07] Error: Got a subscription for missing event "onUserFileChanged"!
[07/09/2020 01:23:07] Error: Got a subscription for missing event "onForceReload"!
[07/09/2020 01:23:07] Error: JS Handler call failed: System.Exception: Tried to call missing handler "cactbotLoadData"!
   at RainbowMage.OverlayPlugin.EventDispatcher.CallHandler(JObject e)
   at RainbowMage.OverlayPlugin.EventDispatcher.ProcessHandlerMessage(IEventReceiver receiver, String data)
[07/09/2020 01:23:07] Error: Got a subscription for missing event "onForceReload"!
[07/09/2020 01:23:07] Error: JS Handler call failed: System.Exception: Tried to call missing handler "cactbotLoadUser"!
   at RainbowMage.OverlayPlugin.EventDispatcher.CallHandler(JObject e)
   at RainbowMage.OverlayPlugin.EventDispatcher.ProcessHandlerMessage(IEventReceiver receiver, String data)
[07/09/2020 01:23:07] Error: Got a subscription for missing event "onUserFileChanged"!
[07/09/2020 01:23:07] Info: Opess: BrowserConsole: Uncaught (in promise) TypeError: Cannot read property 'detail' of null (Source: file:///C:/Users/Admin/AppData/Roaming/Advanced%20Combat%20Tracker/Plugins/OverlayPlugin/cactbot/resources/user_config.js, Line: 35)
[07/09/2020 01:23:08] Info: Raidboss: BrowserConsole: Uncaught (in promise) TypeError: Cannot read property 'detail' of null (Source: file:///C:/Users/Admin/AppData/Roaming/Advanced%20Combat%20Tracker/Plugins/OverlayPlugin/cactbot/resources/user_config.js, Line: 35)
[07/09/2020 01:23:09] Info: skill display: BrowserConsole: ACTWS compatibility shim enabled. (Source: , Line: 28)
[07/09/2020 01:23:11] Info: Found enmity memory for 5.3.

**Comment by quisquous** [comment]
This sounds like `CactbotOverlay.dll` is not enabled.  Is it turned on in your plugins? Is it in the correct order?

**Comment by jenkshi** [comment]
dude thanks for your help btw it says "[07/09/2020 19:59:19] Error: Unable to auto-update due to unknown cactbot directory" do you have any idea how I can fix that ?

**Comment by quisquous** [comment]
You should remove cactbot entirely and then re-add it via Get Plugins: https://github.com/quisquous/cactbot#installing-cactbot

**Comment by quisquous** [comment]
Are you still having issues?

**Comment by quisquous** [comment]
Did you get this fixed?

**Comment by jenkshi** [comment]
Oh sorry for not replyingdude I wasn't online for the past few days. Yes I did fox it thanks for the help really appreciate it man

**Comment by quisquous** [comment]
Thanks! Just wanted to make sure you got it sorted out.  :+1:
