### ISSUE TITLE
load issue 

### ISSUE THREAD

**Issue by chanzie** [quisquous/cactbot#192]
when loading act this is what I end up getting in an error and it wont let me load cactbot anything because of it...
8/7/2018 6:33:30 AM: Info: InitPlugin: PluginDirectory = C:\Program Files (x86)\Advanced Combat Tracker\Overlay Plugin
8/7/2018 6:33:30 AM: Info: LoadAddons: C:\Program Files (x86)\Advanced Combat Tracker\Overlay Plugin\addons\CactbotOverlay.dll
8/7/2018 6:33:30 AM: Error: LoadAddons: C:\Program Files (x86)\Advanced Combat Tracker\Overlay Plugin\addons\CactbotOverlay.dll: System.IO.FileLoadException: Could not load file or assembly 'file:///C:\Program Files (x86)\Advanced Combat Tracker\Overlay Plugin\addons\CactbotOverlay.dll' or one of its dependencies. Operation is not supported. (Exception from HRESULT: 0x80131515)
File name: 'file:///C:\Program Files (x86)\Advanced Combat Tracker\Overlay Plugin\addons\CactbotOverlay.dll' ---> System.NotSupportedException: An attempt was made to load an assembly from a network location which would have caused the assembly to be sandboxed in previous versions of the .NET Framework. This release of the .NET Framework does not enable CAS policy by default, so this load may be dangerous. If this load is not intended to sandbox the assembly, please enable the loadFromRemoteSources switch. See http://go.microsoft.com/fwlink/?LinkId=155569 for more information.
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadFrom(String assemblyFile, Evidence securityEvidence, Byte[] hashValue, AssemblyHashAlgorithm hashAlgorithm, Boolean forIntrospection, Boolean suppressSecurityChecks, StackCrawlMark& stackMark)
   at System.Reflection.Assembly.LoadFrom(String assemblyFile)
   at RainbowMage.OverlayPlugin.PluginMain.LoadAddons()

8/7/2018 6:33:31 AM: Info: InitPlugin: Initialized.

**Comment by chanzie** [comment]
found the problem
