### ISSUE TITLE
Since new update cactbot not loading.

### ISSUE THREAD

**Issue by eparsyl** [quisquous/cactbot#233]
This is the error I get in the plugins log. The error only happens when I update the cactbot with the new 0.8.3 version. The bundled version 0.7.0 that comes with the ACT bundle loads fine. But obviously is outdated. 

9/26/2018 3:04:45 PM: Error: LoadAddons: C:\Program Files (x86)\Advanced Combat Tracker\OverlayPlugin\addons\CactbotOverlay.dll: System.IO.FileLoadException: Could not load file or assembly 'file:///C:\Program Files (x86)\Advanced Combat Tracker\OverlayPlugin\addons\CactbotOverlay.dll' or one of its dependencies. Operation is not supported. (Exception from HRESULT: 0x80131515)
File name: 'file:///C:\Program Files (x86)\Advanced Combat Tracker\OverlayPlugin\addons\CactbotOverlay.dll' ---> System.NotSupportedException: An attempt was made to load an assembly from a network location which would have caused the assembly to be sandboxed in previous versions of the .NET Framework. This release of the .NET Framework does not enable CAS policy by default, so this load may be dangerous. If this load is not intended to sandbox the assembly, please enable the loadFromRemoteSources switch. See http://go.microsoft.com/fwlink/?LinkId=155569 for more information.
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadFrom(String assemblyFile, Evidence securityEvidence, Byte[] hashValue, AssemblyHashAlgorithm hashAlgorithm, Boolean forIntrospection, Boolean suppressSecurityChecks, StackCrawlMark& stackMark)
   at System.Reflection.Assembly.LoadFrom(String assemblyFile)
   at RainbowMage.OverlayPlugin.PluginMain.LoadAddons() in f:\Repositories\OverlayPlugin-Compiler\OverlayPlugin\OverlayPlugin.Core\PluginMain.cs:line 231

**Comment by eparsyl** [comment]
nevermind, i fixed it lol. forgot to "unblock" the new zip file before extracting :p

**Comment by quisquous** [comment]
Glad you got it sorted! :)
