### ISSUE TITLE
TypeError when executing find_missing_translations.py

### ISSUE THREAD

**Issue by Akurosia** [quisquous/cactbot#2541]
node version: v14.15.5
npm version: 6.14.11
python version: Python 3.9.1 (happens also with 3.7.x and 3.8.x)

Steps to reproduce:
1. remove existing node_modules
2. reinstall node_modules by running `npm i`
```
PS F:\Github\cactbot_aku2> npm i

> husky@4.2.5 install F:\Github\cactbot_aku2\node_modules\husky
> node husky install

husky > Setting up git hooks
husky > Done

> husky@4.2.5 postinstall F:\Github\cactbot_aku2\node_modules\husky
> opencollective-postinstall || exit 0

Thank you for using husky!
If you rely on this package, please consider supporting our open collective:
> https://opencollective.com/husky/donate

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules\webpack-dev-server\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

added 1051 packages from 508 contributors and audited 1056 packages in 44.279s

126 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
```
3. reinstall python requirements by using `python -m pip install -r requirements.txt`

```
PS F:\Github\cactbot_aku2> python -m pip install -r requirements.txt
Requirement already satisfied: black==19.10b0 in c:\users\akurosia\appdata\roaming\python\python39\site-packages (from -r requirements.txt (line 2)) (19.10b0)
Requirement already satisfied: pylint==2.5.3 in c:\users\akurosia\appdata\roaming\python\python39\site-packages (from -r requirements.txt (line 3)) (2.5.3)
Requirement already satisfied: PyYAML in c:\users\akurosia\appdata\roaming\python\python39\site-packages (from -r requirements.txt (line 6)) (5.3.1)
Requirement already satisfied: requests in c:\users\akurosia\appdata\roaming\python\python39\site-packages (from -r requirements.txt (line 7)) (2.25.0)
Requirement already satisfied: click>=6.5 in c:\users\akurosia\appdata\roaming\python\python39\site-packages (from black==19.10b0->-r requirements.txt (line 2)) (7.1.2)
Requirement already satisfied: typed-ast>=1.4.0 in c:\python39\lib\site-packages (from black==19.10b0->-r requirements.txt (line 2)) (1.4.1)
Requirement already satisfied: regex in c:\python39\lib\site-packages (from black==19.10b0->-r requirements.txt (line 2)) (2020.11.13)
Requirement already satisfied: toml>=0.9.4 in c:\python39\lib\site-packages (from black==19.10b0->-r requirements.txt (line 2)) (0.10.2)
Requirement already satisfied: attrs>=18.1.0 in c:\users\akurosia\appdata\roaming\python\python39\site-packages (from black==19.10b0->-r requirements.txt (line 2)) (20.3.0)
Requirement already satisfied: appdirs in c:\users\akurosia\appdata\roaming\python\python39\site-packages (from black==19.10b0->-r requirements.txt (line 2)) (1.4.4)
Requirement already satisfied: pathspec<1,>=0.6 in c:\python39\lib\site-packages (from black==19.10b0->-r requirements.txt (line 2)) (0.8.1)
Requirement already satisfied: colorama in c:\users\akurosia\appdata\roaming\python\python39\site-packages (from pylint==2.5.3->-r requirements.txt (line 3)) (0.4.4)
Requirement already satisfied: mccabe<0.7,>=0.6 in c:\python39\lib\site-packages (from pylint==2.5.3->-r requirements.txt (line 3)) (0.6.1)
Requirement already satisfied: astroid<=2.5,>=2.4.0 in c:\users\akurosia\appdata\roaming\python\python39\site-packages (from pylint==2.5.3->-r requirements.txt (line 3)) (2.4.2)
Requirement already satisfied: isort<5,>=4.2.5 in c:\python39\lib\site-packages (from pylint==2.5.3->-r requirements.txt (line 3)) (4.3.21)
Requirement already satisfied: lazy-object-proxy==1.4.* in c:\python39\lib\site-packages (from astroid<=2.5,>=2.4.0->pylint==2.5.3->-r requirements.txt (line 3)) (1.4.3)
Requirement already satisfied: six~=1.12 in c:\python39\lib\site-packages (from astroid<=2.5,>=2.4.0->pylint==2.5.3->-r requirements.txt (line 3)) (1.15.0)
Requirement already satisfied: wrapt~=1.11 in c:\python39\lib\site-packages (from astroid<=2.5,>=2.4.0->pylint==2.5.3->-r requirements.txt (line 3)) (1.12.1)
Requirement already satisfied: chardet<4,>=3.0.2 in c:\users\akurosia\appdata\roaming\python\python39\site-packages (from requests->-r requirements.txt (line 7)) (3.0.4)
Requirement already satisfied: idna<3,>=2.5 in c:\users\akurosia\appdata\roaming\python\python39\site-packages (from requests->-r requirements.txt (line 7)) (2.10)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\python39\lib\site-packages (from requests->-r requirements.txt (line 7)) (1.26.2)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\akurosia\appdata\roaming\python\python39\site-packages (from requests->-r requirements.txt (line 7)) (2020.11.8)
```
4. try running `python .\util\find_missing_translations.py -l de`
```
PS F:\Github\cactbot_aku2> python .\util\find_missing_translations.py -l de
internal/process/esm_loader.js:74
    internalBinding('errors').triggerUncaughtException(
                              ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find module 'F:\Github\cactbot_aku2\resources\regexes' imported from F:\Github\cactbot_aku2\util\find_missing_timeline_translations.js
    at finalizeResolution (internal/modules/esm/resolve.js:276:11)
    at moduleResolve (internal/modules/esm/resolve.js:699:10)
    at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:810:11)
    at Loader.resolve (internal/modules/esm/loader.js:86:40)
    at Loader.getModuleJob (internal/modules/esm/loader.js:230:28)
    at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:56:40)
    at link (internal/modules/esm/module_job.js:55:36) {
  code: 'ERR_MODULE_NOT_FOUND'
}
internal/process/esm_loader.js:74
    internalBinding('errors').triggerUncaughtException(
```

NOTE: `npm run lint` and `npm run test` are worling fine

**Comment by MaikoTan** [comment]
Yes, this is broken since migrating to TS and extensionless import, I think it would be better to refactor this python script into TS, too?

**Comment by VanSlanzar** [comment]
You have the error that I have for several days. She is driving me crazy and I thought it was coming from my pc. I spoke to @quisquous about this because I got really pissed off thinking I was doing something wrong or it was the last update of node or python. I have formating my SSD because of it. I hope a solution will be found.
