### ISSUE TITLE
TypeError with executing `npm run find-translations -- --locale=fr` or other language.

### ISSUE THREAD

**Issue by VanSlanzar** [quisquous/cactbot#2620]
node version: v14.16.0
npm version: 6.14.11
python version: Python 3.9.2

```
Bauer@DESKTOP-SO533H8 MINGW64 ~/Documents/cactbot (main)
$ npm run find-translations -- --locale=fr

> cactbot@ find-translations C:\Users\Bauer\Documents\cactbot
> node --loader ts-node/esm util/find_missing_translations.js "--locale=fr"

(node:172) ExperimentalWarning: --experimental-loader is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)

C:\Users\Bauer\Documents\cactbot\node_modules\ts-node\dist-raw\node-esm-resolve-implementation.js:374
    throw new ERR_MODULE_NOT_FOUND(
          ^
Error: ERR_MODULE_NOT_FOUND C:\Users\Bauer\Documents\cactbot\util\find_missing_timeline_translations C:\Users\Bauer\Documents\cactbot\util\find_missing_translations.js module
    at finalizeResolution (C:\Users\Bauer\Documents\cactbot\node_modules\ts-node\dist-raw\node-esm-resolve-implementation.js:374:11)
    at moduleResolve (C:\Users\Bauer\Documents\cactbot\node_modules\ts-node\dist-raw\node-esm-resolve-implementation.js:809:10)
    at Object.defaultResolve (C:\Users\Bauer\Documents\cactbot\node_modules\ts-node\dist-raw\node-esm-resolve-implementation.js:920:11)
    at C:\Users\Bauer\Documents\cactbot\node_modules\ts-node\src\esm.ts:55:38
    at Generator.next (<anonymous>)
    at C:\Users\Bauer\Documents\cactbot\node_modules\ts-node\dist\esm.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\Bauer\Documents\cactbot\node_modules\ts-node\dist\esm.js:4:12)
    at resolve (C:\Users\Bauer\Documents\cactbot\node_modules\ts-node\dist\esm.js:31:16)
    at Loader.resolve (internal/modules/esm/loader.js:86:40)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cactbot@ find-translations: `node --loader ts-node/esm util/find_missing_translations.js "--locale=fr"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the cactbot@ find-translations script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Bauer\AppData\Roaming\npm-cache\_logs\2021-03-22T21_50_46_914Z-debug.log
```
This is happening today with the merger **into main** of `upstream/main` and `upstream/gh-pages` . Yesterday it was working fine.

**Comment by panicstevenson** [comment]
Is this still happening? I am unable to reproduce this error.

**Comment by VanSlanzar** [comment]
Yes, she's still there. Despite a new install.
