### ISSUE TITLE
Error on `util/check_translation.py` A2,6,8S and A8N

### ISSUE THREAD

**Issue by VanSlanzar** [quisquous/cactbot#2665]
- A2S: from this line, the check is broken.
```
# Enrage
5000.0 "--sync--" sync /03:........:Added new combatant Bombe g▒ante/ window 5000,0
5010.0 "Explosion massive Enrage" sync /:Bombe g▒ante:FDD:/

# Technically this loops, and has a special dialog where Quickthinx says:
Traceback (most recent call last):
  File "C:\Users\Bauer\Documents\Github\cactbot\util\check_translation.py", line 316, in <module>
    main(args)
  File "C:\Users\Bauer\Documents\Github\cactbot\util\check_translation.py", line 273, in main
    print_timeline(args.timeline, timeline_file, trans, args.grep_missing)
  File "C:\Users\Bauer\Documents\Github\cactbot\util\check_translation.py", line 231, in print_timeline
    filter_print_timeline(translate_timeline(line.strip(), trans[locale]), missing_filter)
  File "C:\Users\Bauer\Documents\Github\cactbot\util\check_translation.py", line 245, in filter_print_timeline
    print(text)
  File "C:\Users\Bauer\AppData\Local\Programs\Python\Python39\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2500' in position 60: character maps to <undefined>
```

- A6S: from this line, the check is broken.
```
## Brawler Orb Phase
1500.0 "--sync--" sync / 22:........:Bagarreur:........:Bagarreur:00/ window 500,0
Traceback (most recent call last):
  File "C:\Users\Bauer\Documents\Github\cactbot\util\check_translation.py", line 316, in <module>
    main(args)
  File "C:\Users\Bauer\Documents\Github\cactbot\util\check_translation.py", line 273, in main
    print_timeline(args.timeline, timeline_file, trans, args.grep_missing)
  File "C:\Users\Bauer\Documents\Github\cactbot\util\check_translation.py", line 231, in print_timeline
    filter_print_timeline(translate_timeline(line.strip(), trans[locale]), missing_filter)
  File "C:\Users\Bauer\Documents\Github\cactbot\util\check_translation.py", line 245, in filter_print_timeline
    print(text)
  File "C:\Users\Bauer\AppData\Local\Programs\Python\Python39\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u03b1' in position 24: character maps to <undefined>

```

- A8S: from this line, the check is broken.
```
47.9 "Rayon perp▒tuel" sync /:Attaqueur:162B:/ duration 3.3
Traceback (most recent call last):
  File "C:\Users\Bauer\Documents\Github\cactbot\util\check_translation.py", line 316, in <module>
    main(args)
  File "C:\Users\Bauer\Documents\Github\cactbot\util\check_translation.py", line 273, in main
    print_timeline(args.timeline, timeline_file, trans, args.grep_missing)
  File "C:\Users\Bauer\Documents\Github\cactbot\util\check_translation.py", line 231, in print_timeline
    filter_print_timeline(translate_timeline(line.strip(), trans[locale]), missing_filter)
  File "C:\Users\Bauer\Documents\Github\cactbot\util\check_translation.py", line 245, in filter_print_timeline
    print(text)
  File "C:\Users\Bauer\AppData\Local\Programs\Python\Python39\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u03b2' in position 67: character maps to <undefined>
```

- A8N: from this line, the check is broken.
```
52.5 "M▒garayon" sync /:Attaqueur:1732:/
Traceback (most recent call last):
  File "C:\Users\Bauer\Documents\Github\cactbot\util\check_translation.py", line 316, in <module>
    main(args)
  File "C:\Users\Bauer\Documents\Github\cactbot\util\check_translation.py", line 273, in main
    print_timeline(args.timeline, timeline_file, trans, args.grep_missing)
  File "C:\Users\Bauer\Documents\Github\cactbot\util\check_translation.py", line 231, in print_timeline
    filter_print_timeline(translate_timeline(line.strip(), trans[locale]), missing_filter)
  File "C:\Users\Bauer\Documents\Github\cactbot\util\check_translation.py", line 245, in filter_print_timeline
    print(text)
  File "C:\Users\Bauer\AppData\Local\Programs\Python\Python39\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u03b2' in position 68: character maps to <undefined>
```

**Comment by Akurosia** [comment]
i think this script is not longer really maintained based on the comments here: https://github.com/quisquous/cactbot/pull/1428

**Comment by Akurosia** [comment]
also when i run following command: `python .\check_translation.py -f a8n.js -t fr -gm all` i get the output:
```
0.0 "--Reset--" sync / 21:........:40000010:/ window 10000 jump 0 #MISSINGSYNC
0 "Start" sync /Engage!/ window 0,1 #MISSINGSYNC
206.2 "--targetable--" #MISSINGTEXT
502.1 "--targetable--" #MISSINGTEXT
813.0 "--targetable--" #MISSINGTEXT
899.2 "--untargetable--" #MISSINGTEXT
947.8 "--targetable--" #MISSINGTEXT
1030.9 "--untargetable--" #MISSINGTEXT
1037.1 "--targetable--" #MISSINGTEXT
```

**Comment by quisquous** [comment]
> i think this script is not longer really maintained based on the comments here: #1428

I think it'd be nice to fix it if it's a short fix.  I think the long term plan is write a separate script that does timeline translation if you want to see it, prefer find missing translations for everything else, and then remove check_translation.

**Comment by quisquous** [comment]
@VanSlanzar I think this should fix your issue.  Can you let me know if it doesn't?

**Comment by quisquous** [comment]
> > i think this script is not longer really maintained based on the comments here: #1428
> 
> I think it'd be nice to fix it if it's a short fix. I think the long term plan is write a separate script that does timeline translation if you want to see it, prefer find missing translations for everything else, and then remove check_translation.

Ok, I wrote that script: 4681b56
