### ISSUE TITLE
Load error with cactbot

### ISSUE THREAD

**Issue by Cptbirdseye** [quisquous/cactbot#296]
I'm getting the following error:

22/11/2018 18:49:49: Info: InitPlugin: PluginDirectory = D:\FFXIV Stuff\Advanced Combat Tracker\OverlayPlugin
22/11/2018 18:49:49: Info: LoadAddons: D:\FFXIV Stuff\Advanced Combat Tracker\OverlayPlugin\addons\CactbotOverlay.dll
22/11/2018 18:49:49: Error: LoadAddons: D:\FFXIV Stuff\Advanced Combat Tracker\OverlayPlugin\addons\CactbotOverlay.dll: System.IO.FileLoadException: Could not load file or assembly 'file:///D:\FFXIV Stuff\Advanced Combat Tracker\OverlayPlugin\addons\CactbotOverlay.dll' or one of its dependencies. Operation is not supported. (Exception from HRESULT: 0x80131515)
File name: 'file:///D:\FFXIV Stuff\Advanced Combat Tracker\OverlayPlugin\addons\CactbotOverlay.dll' ---> System.NotSupportedException: An attempt was made to load an assembly from a network location which would have caused the assembly to be sandboxed in previous versions of the .NET Framework. This release of the .NET Framework does not enable CAS policy by default, so this load may be dangerous. If this load is not intended to sandbox the assembly, please enable the loadFromRemoteSources switch. See http://go.microsoft.com/fwlink/?LinkId=155569 for more information.
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadFrom(String assemblyFile, Evidence securityEvidence, Byte[] hashValue, AssemblyHashAlgorithm hashAlgorithm, Boolean forIntrospection, Boolean suppressSecurityChecks, StackCrawlMark& stackMark)
   at System.Reflection.Assembly.LoadFrom(String assemblyFile)
   at RainbowMage.OverlayPlugin.PluginMain.LoadAddons()

22/11/2018 18:49:50: Info: InitPlugin: Initialized.

I didn't get this error with the previous version and all my other plugins are up to date.

**Comment by quisquous** [comment]
Take a look at https://github.com/quisquous/cactbot#potential-errors-and-workarounds for that error message.  I think something is not unblocked.

**Comment by Cptbirdseye** [comment]
Yep I see it now, I have to unblock the new dll.

**Comment by quisquous** [comment]
Glad you got this sorted.  :)
