### ISSUE TITLE
Unable to load network log to raidboss emulator

### ISSUE THREAD

**Issue by shuojwan** [quisquous/cactbot#3180]
I am not able to load network log to the raidboss emulator. There is no response when I click any button. I think WS Server connect is successful, because of the green connection label on the top right. Moreover, when I reload the overlay from ACT, the page got automatically refreshed. I was able to use the emulator to create some custom triggers on June 8, but the emulator stops working at the moment.

There is no error messages in the log:
[6/24/2021 1:30:02 PM] Info: AssemblyResolver: Loaded: Newtonsoft.Json, Version=12.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed
[6/24/2021 1:30:02 PM] Info: AssemblyResolver: Loaded: websocket-sharp, Version=1.0.2.32519, Culture=neutral, PublicKeyToken=5660b08a1845a91e
[6/24/2021 1:30:02 PM] Info: AssemblyResolver: Loaded: HtmlRenderer, Version=0.16.6.0, Culture=neutral, PublicKeyToken=null
[6/24/2021 1:30:02 PM] Info: AssemblyResolver: Loaded: CefSharp, Version=75.1.141.0, Culture=neutral, PublicKeyToken=40c4b6fc221f4138
[6/24/2021 1:30:02 PM] Info: InitPlugin: PluginDirectory = C:\Users\SW\AppData\Roaming\Advanced Combat Tracker\Plugins\OverlayPlugin
[6/24/2021 1:30:03 PM] Info: AssemblyResolver: Loaded: CefSharp.OffScreen, Version=75.1.141.0, Culture=neutral, PublicKeyToken=40c4b6fc221f4138
[6/24/2021 1:30:03 PM] Info: AssemblyResolver: Loaded: CefSharp.Core, Version=75.1.141.0, Culture=neutral, PublicKeyToken=40c4b6fc221f4138
[6/24/2021 1:30:03 PM] Info: InitPlugin: Initialised.
[6/24/2021 1:30:06 PM] Info: cactbot: 0.22.12.0 C:\Users\SW\AppData\Roaming\Advanced Combat Tracker\Plugins\cactbot-0.22.11\cactbot\CactbotOverlay.dll (dir: C:\Users\SW\AppData\Roaming\Advanced Combat Tracker\Plugins\cactbot-0.22.11\cactbot)
[6/24/2021 1:30:06 PM] Info: OverlayPlugin: 0.16.6.0 C:\Users\SW\AppData\Roaming\Advanced Combat Tracker\Plugins\OverlayPlugin\OverlayPlugin.dll
[6/24/2021 1:30:06 PM] Info: FFXIV Plugin: 2.2.0.3 C:\Users\SW\AppData\Roaming\Advanced Combat Tracker\Plugins\FFXIV_ACT_Plugin.dll
[6/24/2021 1:30:06 PM] Info: ACT: 3.5.0.273 C:\Program Files (x86)\Advanced Combat Tracker\Advanced Combat Tracker.exe
[6/24/2021 1:30:06 PM] Info: Parsing Plugin Language: en
[6/24/2021 1:30:06 PM] Info: System Locale: en-US
[6/24/2021 1:30:06 PM] Info: cactbot user directory: C:\Users\SW\AppData\Roaming\Advanced Combat Tracker\Plugins\cactbot-0.22.11\cactbot\user\
[6/24/2021 1:30:06 PM] Info: Version: intl
[6/24/2021 1:30:06 PM] Info: LoadAddons: CactbotOverlay.dll: Initialized Cactbot.PluginLoader
[6/24/2021 1:30:06 PM] Info: WS: Warn: The current logging level has been changed to Info. 

Let me know if you need more information from me.

![emulator](https://user-images.githubusercontent.com/10083630/123327587-70392e80-d4ef-11eb-8892-2483cc110a1e.PNG)

**Comment by valarnin** [comment]
raidemulator isn't really tested in an overlay, we use it pretty much exclusively from a browser.

If you're writing internal cacbot triggers, you can run the source code in a webpack server with `npm run start`.

If you're writing user triggers, you can run it in a normal browser at https://quisquous.github.io/cactbot/ui/raidboss/raidemulator.html?OVERLAY_WS=ws://127.0.0.1:10501/ws.

**Comment by valarnin** [comment]
For reference, the exact breakage here is because OverlayPlugin runs Chromium 75 for overlays, and raidemulator uses a feature that wasn't supported until v76:

![image](https://user-images.githubusercontent.com/6119598/123335107-fd8d7a80-d511-11eb-9670-af88e5b152c0.png)

![image](https://user-images.githubusercontent.com/6119598/123335170-16962b80-d512-11eb-979f-0c85c2230e5c.png)

**Comment by shuojwan** [comment]
Thanks for the quick reply. The Chrome version I use is Version 91.0.4472.114 (Official Build) (64-bit).

I am writing user triggers, and following the guide here: https://github.com/quisquous/cactbot#raidboss-emulator, which points me to a local html file (file://C:/Users/SW/AppData/Roaming/Advanced%20Combat%20Tracker/Plugins/cactbot-0.22.11/cactbot/ui/raidboss/raidboss.html?OVERLAY_WS=ws://127.0.0.1:10501/ws).

The link (https://quisquous.github.io/cactbot/ui/raidboss/raidemulator.html?OVERLAY_WS=ws://127.0.0.1:10501/ws) works for me, which unblocks me for now.

**Comment by shuojwan** [comment]
Actually I saw the error from Chrome:

Uncaught (in promise) DOMException: Failed to construct 'Worker': Script at 'file:///C:/Users/SW/AppData/Roaming/Advanced%20Combat%20Tracker/Plugins/cactbot-0.22.11/cactbot/NetworkLogConverter.worker.bundle.worker.js' cannot be accessed from origin 'null'.
    at new Worker_fn (file:///C:/Users/SW/AppData/Roaming/Advanced%20Combat%20Tracker/Plugins/cactbot-0.22.11/cactbot/ui/raidboss/raidemulator.bundle.js:8852:10)
    at HTMLDocument.<anonymous> (file:///C:/Users/SW/AppData/Roaming/Advanced%20Combat%20Tracker/Plugins/cactbot-0.22.11/cactbot/ui/raidboss/raidemulator.bundle.js:8963:30)

**Comment by valarnin** [comment]
Does that error happen with the github.io link? Or only with local?

**Comment by shuojwan** [comment]
The error only occurs at local. github.io works for me perfectly.

**Comment by valarnin** [comment]
Alright, probably we should just update the documentation to point directly to the github.io link instead of pointing at the local file. @quisquous do you agree?

**Comment by valarnin** [comment]
I guess technically we could skirt around the whole issue by just reconstructing the objects on the other side via `Object.assign` instead?

**Comment by quisquous** [comment]
> Alright, probably we should just update the documentation to point directly to the github.io link instead of pointing at the local file. @quisquous do you agree?

Yeah, it sounds like workers can't be used from `file://` origins.  I think the documentation should suggest to either use `npm start` and the dev build or the github.io link (or maybe just the github.io link)?

> I guess technically we could skirt around the whole issue by just reconstructing the objects on the other side via `Object.assign` instead?

Is this a reply to #3181? I don't think it fixes https://github.com/quisquous/cactbot/issues/3180#issuecomment-867970802 if that's what you're saying.

**Comment by valarnin** [comment]
> Is this a reply to #3181? I don't think it fixes #3180 (comment) if that's what you're saying.
Yes, I don't know how exactly it ended up here 🤷
