### ISSUE TITLE
raidemulator: failed to import fights with Dexie

### ISSUE THREAD

**Issue by quisquous** [quisquous/cactbot#3220]
I found this with the log from #3156, but I suspect any log will have this issue.

dexie.mjs:1270 Unhandled rejection: DataCloneError: Failed to execute 'add' on 'IDBObjectStore': () => msg.data.name could not be cloned.
 DataCloneError: Failed to execute 'add' on 'IDBObjectStore': () => msg.data.name could not be cloned.
Error: Failed to execute 'add' on 'IDBObjectStore': () => msg.data.name could not be cloned.
    at http://localhost:8080/ui/raidboss/raidemulator.bundle.js:7265:44
    at executePromiseTask (http://localhost:8080/ui/raidboss/raidemulator.bundle.js:5147:9)
    at new DexiePromise (http://localhost:8080/ui/raidboss/raidemulator.bundle.js:4961:5)
    at Object.mutate (http://localhost:8080/ui/raidboss/raidemulator.bundle.js:7217:20)
    at Object.mutate (http://localhost:8080/ui/raidboss/raidemulator.bundle.js:8220:38)
    at http://localhost:8080/ui/raidboss/raidemulator.bundle.js:5780:31
    at checkTableInTransaction (http://localhost:8080/ui/raidboss/raidemulator.bundle.js:5637:20)
    at http://localhost:8080/ui/raidboss/raidemulator.bundle.js:5580:24
    at usePSD (http://localhost:8080/ui/raidboss/raidemulator.bundle.js:5495:16)
    at newScope (http://localhost:8080/ui/raidboss/raidemulator.bundle.js:5399:14)
From previous: 
    at Object.mutate (http://localhost:8080/ui/raidboss/raidemulator.bundle.js:7217:20)
    at Object.mutate (http://localhost:8080/ui/raidboss/raidemulator.bundle.js:8220:38)
    at http://localhost:8080/ui/raidboss/raidemulator.bundle.js:5780:31
    at checkTableInTransaction (http://localhost:8080/ui/raidboss/raidemulator.bundle.js:5637:20)
    at http://localhost:8080/ui/raidboss/raidemulator.bundle.js:5580:24
    at usePSD (http://localhost:8080/ui/raidboss/raidemulator.bundle.js:5495:16)
    at newScope (http://localhost:8080/ui/raidboss/raidemulator.bundle.js:5399:14)
    at http://localhost:8080/ui/raidboss/raidemulator.bundle.js:5578:20

**Comment by shuojwan** [comment]
I got the same error this morning. When will the fix be in effect?

**Comment by valarnin** [comment]
PR for the fix is open. If you're running locally you can grab the patch from the PR and apply yourself manually, otherwise you'll have to wait for quis to merge the PR.
