### ISSUE TITLE
Raid Emulator: Transaction is Readonly When Loading Old Encounters

### ISSUE THREAD

**Issue by panicstevenson** [quisquous/cactbot#3231]
## Description

Attempting to load old encounters (pre-Dexie, as I understand) returns the following:
```
Unhandled rejection: ReadOnlyError: Transaction is readonly
    at Transaction$$1.Transaction._promise (http://localhost:8080/ui/raidboss/raidemulator.bundle.js:6613:30)
    at Table$$1.Table._trans (http://localhost:8080/ui/raidboss/raidemulator.bundle.js:5302:27)
    at Table$$1.Table.put (http://localhost:8080/ui/raidboss/raidemulator.bundle.js:5475:21)
    at Object.get (http://localhost:8080/ui/raidboss/raidemulator.bundle.js:29624:63)
From previous: 
    at DexiePromise.then (http://localhost:8080/ui/raidboss/raidemulator.bundle.js:4629:22)
    at Table$$1.Table.put (http://localhost:8080/ui/raidboss/raidemulator.bundle.js:5476:14)
    at Object.get (http://localhost:8080/ui/raidboss/raidemulator.bundle.js:29624:63)
```

Additionally, attempting to export the database to reimport it, I receive:

```
Aw, Snap!

Something went wrong while displaying this webpage.

Error code: SBOX_FATAL_MEMORY_EXCEEDED
```

## Additional information

Encountered this error while testing my merge commit (`2139cea`) of PR 3131.

I can load network logs of fights that have happened before the Dexie change and use them as expected, but things that exist within the database from before the Dexie change cannot be loaded via the Load Encounter button.

**Comment by valarnin** [comment]
To clarify, are these encounters that trigger the encounter version upgrade code?

https://github.com/quisquous/cactbot/blob/main/ui/raidboss/emulator/data/Encounter.ts#L129-L143

**Comment by panicstevenson** [comment]
> To clarify, are these encounters that trigger the encounter version upgrade code?

It seems like it? Unsure what I'm looking for other than it reaches that code.
