### ISSUE TITLE
LoadAddons: CactbotOverlay.dll: System.ArgumentNullException: String reference not set to an instance of a String.

### ISSUE THREAD

**Issue by shuojwan** [quisquous/cactbot#3306]
[7/15/2021 9:02:40 PM] Info: AssemblyResolver: Loaded: Newtonsoft.Json, Version=12.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed
[7/15/2021 9:02:40 PM] Info: AssemblyResolver: Loaded: websocket-sharp, Version=1.0.2.32519, Culture=neutral, PublicKeyToken=5660b08a1845a91e
[7/15/2021 9:02:40 PM] Info: AssemblyResolver: Loaded: HtmlRenderer, Version=0.16.6.0, Culture=neutral, PublicKeyToken=null
[7/15/2021 9:02:40 PM] Info: AssemblyResolver: Loaded: CefSharp, Version=75.1.141.0, Culture=neutral, PublicKeyToken=40c4b6fc221f4138
[7/15/2021 9:02:40 PM] Info: InitPlugin: PluginDirectory = C:\Users\SW\AppData\Roaming\Advanced Combat Tracker\Plugins\OverlayPlugin
[7/15/2021 9:02:40 PM] Info: AssemblyResolver: Loaded: CefSharp.OffScreen, Version=75.1.141.0, Culture=neutral, PublicKeyToken=40c4b6fc221f4138
[7/15/2021 9:02:40 PM] Info: AssemblyResolver: Loaded: CefSharp.Core, Version=75.1.141.0, Culture=neutral, PublicKeyToken=40c4b6fc221f4138
[7/15/2021 9:02:40 PM] Info: InitPlugin: Initialised.
[7/15/2021 9:02:44 PM] Error: LoadAddons: CactbotOverlay.dll: System.ArgumentNullException: String reference not set to an instance of a String.
Parameter name: name
   at System.Globalization.CultureInfo..ctor(String name, Boolean useUserOverride)
   at Cactbot.CactbotEventSource.Start()
   at RainbowMage.OverlayPlugin.Registry.StartEventSource[T](T source)
   at RainbowMage.OverlayPlugin.PluginMain.LoadAddons()
[7/15/2021 9:02:48 PM] Info: Found enmity memory for 5.5.

**Comment by shuojwan** [comment]
This issue started occurring after the recent update. Currently Cactbot cannot be loaded at all for me.

**Comment by JLGarber** [comment]
A lot of things got shuffled around with the latest release, and it looks like the language selection in the plugin initializer is unhappy with what it's being fed. We'll just have to sit tight until that's fixed, although that shouldn't be too long if we're lucky.

**Comment by MaikoTan** [comment]
So this bug occurred because the language setting comes `null` or something?
I am not very sure since my C# knowledge is poor, but shouldn't it be handled by checking the variable `ui_lang` equals `null` or not, rather than just a `try-catch`?

**Comment by quisquous** [comment]
Oh yes, I definitely agree that catching null is better.  However, the bug wasn't reproducing for me and it wasn't clear to me why so many people (2 in github issues, 3-4 on discord) were running into this.  I think the only way you would get null there is if the plugin language detection failed?  And why is that happening for so many people? If @JLGarber has time, maybe he can do some debugging (or try a test build with debugging?) because I wasn't seeing this on my computer.

So, I wanted a heavy-handed fix that I knew would work so that I could re-release quickly and left a `// TODO: MaikoTan sorry about this maybe you can make it better` sort of comment.
