### ISSUE TITLE
rdmty not parsing

### ISSUE THREAD

**Issue by Cptbirdseye** [quisquous/cactbot#342]
I noticed that the past few weeks rdmty only shows "Awaiting data" and doesn't parse anything.  I think this error is being generated by it:

24/01/2019 18:44:10: Error: Mini Parse: Update: System.NullReferenceException: Object reference not set to an instance of an object.
   at RainbowMage.OverlayPlugin.Overlays.MiniParseOverlay.CreateJsonData()
   at RainbowMage.OverlayPlugin.Overlays.MiniParseOverlay.CreateEventDispatcherScript()
   at RainbowMage.OverlayPlugin.Overlays.MiniParseOverlay.Update()
   at RainbowMage.OverlayPlugin.OverlayBase`1.<InitializeTimer>b__10(Object o, ElapsedEventArgs e)

**Comment by quisquous** [comment]
Hmm.  I'm not sure about that particular error message, but one thing that a lot of folks have run into in the last release is that I flipped the default for the "dps update rate" from 3 to 0 because folks were having performance issues.  On your overlay config panel for rdmty, is the dps update rate greater than zero?

**Comment by Cptbirdseye** [comment]
Mine is at 0, ah...

**Comment by quisquous** [comment]
Aha! Let me know if that fixes it or not.

**Comment by Cptbirdseye** [comment]
Yes, haha.  Thank you.
