### ISSUE TITLE
test_timeline errors with newer files

### ISSUE THREAD

**Issue by quisquous** [quisquous/cactbot#3499]
Assuming this is a "newer file" issue, but am not sure.  It still works on older files from 2017/2018.

Here's a recent log: [TheRoyalCityOfRabanastre_20211003_003838_25m48s.log](https://github.com/quisquous/cactbot/files/7272517/TheRoyalCityOfRabanastre_20211003_003838_25m48s.log)

If you apply #3497, then you only get this, but you should get much more (and it worked in game, from this log):
```
$ python util/test_timeline.py -f TheRoyalCityOfRabanastre_20211003_003838_25m48s.log -t royal_city_of_rabanastre -lf 2
0.000: Matched entry: 1000.0 --start-- (+1000.000s)gi
1038.711: Matched entry: 1039.4 Towerfall (+0.689s)←[33m←[0m
    Warning: 38.711s since last sync
    Missed sync: --sync-- at 1011.0
    Missed sync: Quake IV at 1015.0
    Missed sync: Control Tower x1 at 1028.6
    Missed sync: Sanction at 1031.8
1085.471: Matched entry: 1108.4 Impact (+22.929s)
    Warning: 46.071s since last sync
    Missed sync: Extreme Edge at 1046.2
    Missed sync: Earth Hammer at 1056.1
    Missed sync: Hammerfall at 1064.3
    Missed sync: Quake IV at 1073.3
    Missed sync: Rock Cutter at 1082.6
    Missed sync: --sync-- at 1087.0
    Missed sync: Command Tower at 1090.0
    Missed sync: Earth Shaker at 1101.3 (last seen at 1084.448)
    Missed sync: Earth Shaker at 1106.2 (last seen at 1084.448)
1113.436: Matched entry: 1135.8 Impact (+22.364s)
    Missed sync: Falling Boulder at 1128.5
```

Bonus error: running without #3497 
```
$ python util/test_timeline.py -f TheRoyalCityOfRabanastre_20211003_003838_25m48s.log -t royal_city_of_rabanastre -lf 2
Traceback (most recent call last):
  File "util/test_timeline.py", line 592, in <module>
    main(args)
  File "util/test_timeline.py", line 450, in main
    run_file(args, timelist)
  File "util/test_timeline.py", line 414, in run_file
    state = check_event(line, timelist, state)
  File "util/test_timeline.py", line 304, in check_event
    match = test_match(event, entry)
  File "util/test_timeline.py", line 205, in test_match
    and re.search(entry["regex"], get_regex(event))
  [...] snip some re.py stuff
re.error: unknown extension ?\| at position 17
```

**Comment by quisquous** [comment]
The python version of this script no longer exists.
