### ISSUE TITLE
Bug: `npm run test` raise ERR_MODULE_NOT_FOUND error (node v16.13.0)

### ISSUE THREAD

**Issue by Bing-su** [quisquous/cactbot#3616]
I've only used lint and lintfix so far, but I found this error this time.
## Description
`npm run test` raise ERR_MODULE_NOT_FOUND error (node v16.13.0)

## Environment
- OS: Windows 11
- nodejs: 16.13.0 (nodejs-lts latest)
- npm: 7.21.0
- shell: Windows Terminal (powershell)

set npm script shell to git bash
```
# ~/.npmrc

script-shell="C:\\Program Files\\Git\\bin\\bash.exe"
shell="C:\\Program Files\\Git\\bin\\bash.exe"
```

In ubuntu(WSL2), node v14.17.3, npm v6.14.13, the below error does not occur.

## What I done

0. I cloned cactbot repo again for this issue.

1. run `npm install` in cactbot dir

<details>
<summary>npm install log</summary>

```sh
cactbot on  main is 📦 v0.23.8 via 🐍 v3.8.12
❯ npm install
npm WARN old lockfile
npm WARN old lockfile The package-lock.json file was created with an old version of npm,
npm WARN old lockfile so supplemental metadata must be fetched from the registry.
npm WARN old lockfile This is a one-time fix-up, please be patient...
npm WARN old lockfile
npm WARN deprecated @stylelint/postcss-markdown@0.36.2: Use the original unforked package instead: postcss-markdown
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm WARN deprecated debug@3.2.6: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm WARN deprecated debug@3.2.6: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.

added 1638 packages, and audited 1639 packages in 4m

190 packages are looking for funding
  run `npm fund` for details

42 vulnerabilities (17 moderate, 25 high)

To address issues that do not require attention, run:
  npm audit fix

To address all issues possible (including breaking changes), run:
  npm audit fix --force

Some issues need review, and may require choosing
a different dependency.

Run `npm audit` for details.
```
</details>

it changed `package-lock.json` file.

![](https://i.imgur.com/8vo1UtR.png)

2. npm run test

<details>
<summary>npm run test log</summary>

```sh
cactbot on  main [!] is 📦 v0.23.8 via 🐍 v3.8.12
❯ npm run test

> cactbot@0.23.8 test
> node_modules/.bin/mocha

(node:13404) ExperimentalWarning: --experimental-loader is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
(node:13404) DeprecationWarning: Obsolete loader hook(s) supplied and will be ignored: getFormat, transformSource

Error: ERR_MODULE_NOT_FOUND D:\git_repo\cactbot\test\helper\test_manifest D:\git_repo\cactbot\test\test_raidboss_data.js module
    at finalizeResolution (D:\git_repo\cactbot\node_modules\ts-node\dist-raw\node-esm-resolve-implementation.js:374:11)
    at moduleResolve (D:\git_repo\cactbot\node_modules\ts-node\dist-raw\node-esm-resolve-implementation.js:809:10)
    at Object.defaultResolve (D:\git_repo\cactbot\node_modules\ts-node\dist-raw\node-esm-resolve-implementation.js:920:11)
    at D:\git_repo\cactbot\node_modules\ts-node\src\esm.ts:55:38
    at Generator.next (<anonymous>)
    at D:\git_repo\cactbot\node_modules\ts-node\dist\esm.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (D:\git_repo\cactbot\node_modules\ts-node\dist\esm.js:4:12)
    at resolve (D:\git_repo\cactbot\node_modules\ts-node\dist\esm.js:31:16)
    at ESMLoader.resolve (node:internal/modules/esm/loader:422:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:222:40)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:76:40)
    at link (node:internal/modules/esm/module_job:75:36)
```

</details>

3. run other scripts as they seem to have errors.

#### work
```sh
npm run start
npm run version
npm run build
npm run build-gh-pages
npm run tsc-no-emit
npm run lint
npm run lintfix
npm run stylelint
npm run markdownlint
npm run lint-staged
```

#### error

`npm run util`

<details>
<summary>npm run util log</summary>

```sh
cactbot on  main [!] is 📦 v0.23.8 via 🐍 v3.8.12
❯ npm run util

> cactbot@0.23.8 util
> node --loader ts-node/esm util/index.ts

(node:36316) ExperimentalWarning: --experimental-loader is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
TypeError: Unknown file extension ".ts" for D:\git_repo\cactbot\util\index.ts
    at new NodeError (node:internal/errors:371:5)
    at Object.file: (node:internal/modules/esm/get_format:72:15)
    at defaultGetFormat (node:internal/modules/esm/get_format:85:38)
    at defaultLoad (node:internal/modules/esm/load:13:42)
    at ESMLoader.load (node:internal/modules/esm/loader:303:26)
    at ESMLoader.moduleProvider (node:internal/modules/esm/loader:230:58)
    at new ModuleJob (node:internal/modules/esm/module_job:63:26)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:244:11)
    at async Promise.all (index 0)
    at ESMLoader.import (node:internal/modules/esm/loader:281:24)
```

</details>

`npm run coverage-report`

<details>
<summary>npm run coverage-report log</summary>

```sh
cactbot on  main [!] is 📦 v0.23.8 via 🐍 v3.8.12 took 3s
❯ npm run coverage-report

> cactbot@0.23.8 coverage-report
> node --loader ts-node/esm util/gen_coverage_report.js

(node:11732) ExperimentalWarning: --experimental-loader is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
(node:11732) DeprecationWarning: Obsolete loader hook(s) supplied and will be ignored: getFormat, transformSource

D:\git_repo\cactbot\node_modules\ts-node\dist-raw\node-esm-resolve-implementation.js:374
    throw new ERR_MODULE_NOT_FOUND(
          ^
Error: ERR_MODULE_NOT_FOUND D:\git_repo\cactbot\resources\zone_info D:\git_repo\cactbot\util\gen_coverage_report.js module
    at finalizeResolution (D:\git_repo\cactbot\node_modules\ts-node\dist-raw\node-esm-resolve-implementation.js:374:11)
    at moduleResolve (D:\git_repo\cactbot\node_modules\ts-node\dist-raw\node-esm-resolve-implementation.js:809:10)
    at Object.defaultResolve (D:\git_repo\cactbot\node_modules\ts-node\dist-raw\node-esm-resolve-implementation.js:920:11)
    at D:\git_repo\cactbot\node_modules\ts-node\src\esm.ts:55:38
    at Generator.next (<anonymous>)
    at D:\git_repo\cactbot\node_modules\ts-node\dist\esm.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (D:\git_repo\cactbot\node_modules\ts-node\dist\esm.js:4:12)
    at resolve (D:\git_repo\cactbot\node_modules\ts-node\dist\esm.js:31:16)
    at ESMLoader.resolve (node:internal/modules/esm/loader:422:30)
```

</details>

`npm run fetch-deps`

<details>
<summary>npm run fetch-deps log</summary>

```sh
cactbot on  main [!] is 📦 v0.23.8 via 🐍 v3.8.12
❯ npm run fetch-deps

> cactbot@0.23.8 fetch-deps
> node --loader ts-node/esm ./util/fetch_deps.ts

(node:43076) ExperimentalWarning: --experimental-loader is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
TypeError: Unknown file extension ".ts" for D:\git_repo\cactbot\util\fetch_deps.ts
    at new NodeError (node:internal/errors:371:5)
    at Object.file: (node:internal/modules/esm/get_format:72:15)
    at defaultGetFormat (node:internal/modules/esm/get_format:85:38)
    at defaultLoad (node:internal/modules/esm/load:13:42)
    at ESMLoader.load (node:internal/modules/esm/loader:303:26)
    at ESMLoader.moduleProvider (node:internal/modules/esm/loader:230:58)
    at new ModuleJob (node:internal/modules/esm/module_job:63:26)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:244:11)
    at async Promise.all (index 0)
    at ESMLoader.import (node:internal/modules/esm/loader:281:24)
```

</details>

`npm run generate-log-guide`

<details>
<summary>npm run generate-log-guide log</summary>

```sh
cactbot on  main [!] is 📦 v0.23.8 via 🐍 v3.8.12
❯ npm run generate-log-guide

> cactbot@0.23.8 generate-log-guide
> node --loader ts-node/esm util/gen_log_guide.ts

(node:42304) ExperimentalWarning: --experimental-loader is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
TypeError: Unknown file extension ".ts" for D:\git_repo\cactbot\util\gen_log_guide.ts
    at new NodeError (node:internal/errors:371:5)
    at Object.file: (node:internal/modules/esm/get_format:72:15)
    at defaultGetFormat (node:internal/modules/esm/get_format:85:38)
    at defaultLoad (node:internal/modules/esm/load:13:42)
    at ESMLoader.load (node:internal/modules/esm/loader:303:26)
    at ESMLoader.moduleProvider (node:internal/modules/esm/loader:230:58)
    at new ModuleJob (node:internal/modules/esm/module_job:63:26)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:244:11)
    at async Promise.all (index 0)
    at ESMLoader.import (node:internal/modules/esm/loader:281:24)
```

</details>

`npm run process-triggers`

<details>
<summary>npm run process-triggers log</summary>

```sh
cactbot on  main [!] is 📦 v0.23.8 via 🐍 v3.8.12
❯ npm run process-triggers

> cactbot@0.23.8 process-triggers
> node --loader ts-node/esm util/process_triggers_folder.js

(node:35376) ExperimentalWarning: --experimental-loader is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
TypeError: Unknown file extension ".ts" for D:\git_repo\cactbot\util\process_triggers_folder.ts
    at new NodeError (node:internal/errors:371:5)
    at Object.file: (node:internal/modules/esm/get_format:72:15)
    at defaultGetFormat (node:internal/modules/esm/get_format:85:38)
    at defaultLoad (node:internal/modules/esm/load:13:42)
    at ESMLoader.load (node:internal/modules/esm/loader:303:26)
    at ESMLoader.moduleProvider (node:internal/modules/esm/loader:230:58)
    at new ModuleJob (node:internal/modules/esm/module_job:63:26)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:244:11)
    at async Promise.all (index 0)
    at ESMLoader.import (node:internal/modules/esm/loader:281:24)
```

</details>

**Comment by quisquous** [comment]
The `engines` field in `package.json` suggests `>=14.15.0`.  Have you tried an earlier `14.x.x` version?  It's possible that there are changes in node 16 that cactbot has not been adjusted to work with yet.

**Comment by VanSlanzar** [comment]
I come to post here in cohesion with my post on npm install. Version 14.15.0 works fine. Thank you.

**Comment by Bing-su** [comment]
Thanks. node 14.17.3, npm 6.14.13, it works fine. How about mentioning that higher (>= 16) version of node can cause problems in `CONTRIBUTING.md` or else?

**Comment by MaikoTan** [comment]
I think since the v16 is the LTS version, we should fix this error and upgrade the lockfile version later.
But it seems fine on Linux? At least on my Debian and Arch Linux it works file with both nodejs LTS version and npm v7.
