### ISSUE TITLE
Error with `npm run test` and other

### ISSUE THREAD

**Issue by VanSlanzar** [quisquous/cactbot#3680]
Sorry, i not understand why i have this error. I need help. Thank you.

```
$ npm run test

> cactbot@0.23.10 test C:\Users\gamer\Documents\GitHub\cactbot
> mocha

(node:24356) ExperimentalWarning: --experimental-loader is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)

C:\Users\gamer\Documents\GitHub\cactbot\node_modules\ts-node\src\index.ts:513
    return new TSError(diagnosticText, diagnosticCodes)
           ^
TSError: ⨯ Unable to compile TypeScript:
error TS5083: Cannot read file 'C:/Users/gamer/Documents/GitHub/cactbot/tsconfig.base.json'.

    at createTSError (C:\Users\gamer\Documents\GitHub\cactbot\node_modules\ts-node\src\index.ts:513:12)
    at reportTSError (C:\Users\gamer\Documents\GitHub\cactbot\node_modules\ts-node\src\index.ts:517:19)
    at create (C:\Users\gamer\Documents\GitHub\cactbot\node_modules\ts-node\src\index.ts:528:36)
    at Object.register (C:\Users\gamer\Documents\GitHub\cactbot\node_modules\ts-node\src\index.ts:410:19)
    at Object.registerAndCreateEsmHooks (C:\Users\gamer\Documents\GitHub\cactbot\node_modules\ts-node\src\esm.ts:11:26)
    at file:///C:/Users/gamer/Documents/GitHub/cactbot/node_modules/ts-node/esm.mjs:7:58
    at ModuleJob.run (internal/modules/esm/module_job.js:146:23)
    at Loader.import (internal/modules/esm/loader.js:165:24)
    at internal/process/esm_loader.js:57:9
    at Object.loadESM (internal/process/esm_loader.js:67:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cactbot@0.23.10 test: `mocha`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the cactbot@0.23.10 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\gamer\AppData\Roaming\npm-cache\_logs\2021-11-24T23_23_02_021Z-debug.log
```
```
$ npm run find-translations -- --locale=fr -f e1s.js

> cactbot@0.23.10 find-translations C:\Users\gamer\Documents\GitHub\cactbot
> npm run util -- findTranslations "--locale=fr" "-f" "e1s.js"


> cactbot@0.23.10 util C:\Users\gamer\Documents\GitHub\cactbot
> node --loader ts-node/esm util/index.ts "findTranslations" "--locale=fr" "-f" "e1s.js"

(node:11736) ExperimentalWarning: --experimental-loader is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)

C:\Users\gamer\Documents\GitHub\cactbot\node_modules\ts-node\src\index.ts:513
    return new TSError(diagnosticText, diagnosticCodes)
           ^
TSError: ⨯ Unable to compile TypeScript:
error TS5083: Cannot read file 'C:/Users/gamer/Documents/GitHub/cactbot/tsconfig.base.json'.

    at createTSError (C:\Users\gamer\Documents\GitHub\cactbot\node_modules\ts-node\src\index.ts:513:12)
    at reportTSError (C:\Users\gamer\Documents\GitHub\cactbot\node_modules\ts-node\src\index.ts:517:19)
    at create (C:\Users\gamer\Documents\GitHub\cactbot\node_modules\ts-node\src\index.ts:528:36)
    at Object.register (C:\Users\gamer\Documents\GitHub\cactbot\node_modules\ts-node\src\index.ts:410:19)
    at Object.registerAndCreateEsmHooks (C:\Users\gamer\Documents\GitHub\cactbot\node_modules\ts-node\src\esm.ts:11:26)
    at file:///C:/Users/gamer/Documents/GitHub/cactbot/node_modules/ts-node/esm.mjs:7:58
    at ModuleJob.run (internal/modules/esm/module_job.js:146:23)
    at Loader.import (internal/modules/esm/loader.js:165:24)
    at internal/process/esm_loader.js:57:9
    at Object.loadESM (internal/process/esm_loader.js:67:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cactbot@0.23.10 util: `node --loader ts-node/esm util/index.ts "findTranslations" "--locale=fr" "-f" "e1s.js"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the cactbot@0.23.10 util script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\gamer\AppData\Roaming\npm-cache\_logs\2021-11-24T23_27_42_086Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cactbot@0.23.10 find-translations: `npm run util -- findTranslations "--locale=fr" "-f" "e1s.js"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the cactbot@0.23.10 find-translations script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\gamer\AppData\Roaming\npm-cache\_logs\2021-11-24T23_27_42_121Z-debug.log
```
```
$ npm run translate-timeline -- --locale=fr --timeline=e1s

> cactbot@0.23.10 translate-timeline C:\Users\gamer\Documents\GitHub\cactbot
> npm run util -- translateTimeline "--locale=fr" "--timeline=e1s"


> cactbot@0.23.10 util C:\Users\gamer\Documents\GitHub\cactbot
> node --loader ts-node/esm util/index.ts "translateTimeline" "--locale=fr" "--timeline=e1s"

(node:10620) ExperimentalWarning: --experimental-loader is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)

C:\Users\gamer\Documents\GitHub\cactbot\node_modules\ts-node\src\index.ts:513
    return new TSError(diagnosticText, diagnosticCodes)
           ^
TSError: ⨯ Unable to compile TypeScript:
error TS5083: Cannot read file 'C:/Users/gamer/Documents/GitHub/cactbot/tsconfig.base.json'.

    at createTSError (C:\Users\gamer\Documents\GitHub\cactbot\node_modules\ts-node\src\index.ts:513:12)
    at reportTSError (C:\Users\gamer\Documents\GitHub\cactbot\node_modules\ts-node\src\index.ts:517:19)
    at create (C:\Users\gamer\Documents\GitHub\cactbot\node_modules\ts-node\src\index.ts:528:36)
    at Object.register (C:\Users\gamer\Documents\GitHub\cactbot\node_modules\ts-node\src\index.ts:410:19)
    at Object.registerAndCreateEsmHooks (C:\Users\gamer\Documents\GitHub\cactbot\node_modules\ts-node\src\esm.ts:11:26)
    at file:///C:/Users/gamer/Documents/GitHub/cactbot/node_modules/ts-node/esm.mjs:7:58
    at ModuleJob.run (internal/modules/esm/module_job.js:146:23)
    at Loader.import (internal/modules/esm/loader.js:165:24)
    at internal/process/esm_loader.js:57:9
    at Object.loadESM (internal/process/esm_loader.js:67:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cactbot@0.23.10 util: `node --loader ts-node/esm util/index.ts "translateTimeline" "--locale=fr" "--timeline=e1s"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the cactbot@0.23.10 util script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\gamer\AppData\Roaming\npm-cache\_logs\2021-11-24T23_28_44_386Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cactbot@0.23.10 translate-timeline: `npm run util -- translateTimeline "--locale=fr" "--timeline=e1s"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the cactbot@0.23.10 translate-timeline script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\gamer\AppData\Roaming\npm-cache\_logs\2021-11-24T23_28_44_406Z-debug.log
```

**Comment by VanSlanzar** [comment]
Well, after several unsuccessful attempts, I deleted all the repositories and went back to something clean. It works.

**Comment by quisquous** [comment]
Sorry for forgetting about this issue.  I am glad you got this figured out.

**Comment by VanSlanzar** [comment]
Do not worry. In the end, deleting and recloning the repositories (web and pc) was the best solution. I think I created some problems myself when I started out in my contribution, which got bigger with all of our modifications. Now everything is working fine.
