### ISSUE TITLE
OverlayPluginName: Update: System.MissingMethodException: Method Not Found

### ISSUE THREAD

**Issue by Nephera** [quisquous/cactbot#383]
3/12/2019 9:50:24 PM: Error: Raid: Update: System.MissingMethodException: Method not found: '!!0[] System.Array.Empty()'.
   at Cactbot.CactbotOverlay.Initialize()
   at Cactbot.CactbotOverlay.Update()
   at RainbowMage.OverlayPlugin.OverlayBase`1.<InitializeTimer>b__10(Object o, ElapsedEventArgs e) in f:\Repositories\OverlayPlugin-Compiler\OverlayPlugin\OverlayPlugin.Core\OverlayBase.cs:line 234

**Comment by quisquous** [comment]
This seems like it might be the same as issue #100, that you have the wrong .NET framework version installed.

**Comment by Nephera** [comment]
Updated to .NET Framework 4.7.2, worked like a charm.  Thank you.

**Comment by quisquous** [comment]
:+1: Thanks for letting me know.  I added this error message to the main readme, so hopefully other folks won't have the same confusion.
