### ISSUE TITLE
Errors in Console

### ISSUE THREAD

**Issue by TKDBB84** [quisquous/cactbot#50]
Everything seems to be functioning as expected, but getting odd error output in the overlay console.

 Error: Cactbot: Exception in SendFastRateEvents: Could not load file or assembly 'FFXIV_ACT_Plugin, Version=1.4.2.28, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.

Error: Cactbot: Stack:    at Cactbot.CactbotOverlay.SendFastRateEvents()
   at Cactbot.CactbotOverlay.<.ctor>b__75_0(Object o, ElapsedEventArgs args)

Error: Cactbot: Source: CactbotOverlay

**I should mention this is with the DLL unblocked, the plugin is working, but the errors display regardless.**

Running:
Cactbot 0.6.21
Overlay: 0.3.4.0
FFXIV: 1.6.2.5

full output:
```
2/14/2018 8:23:09 PM: Info: InitPlugin: PluginDirectory = C:\Program Files (x86)\Advanced Combat Tracker
2/14/2018 8:23:09 PM: Info: LoadAddons: C:\Program Files (x86)\Advanced Combat Tracker\addons\CactbotOverlay.dll
2/14/2018 8:23:09 PM: Info: LoadAddons: Cactbot.OverlayAddonMain: Initialized
2/14/2018 8:23:09 PM: Info: LoadAddons: C:\Program Files (x86)\Advanced Combat Tracker\addons\EnmityOverlay.dll
2/14/2018 8:23:09 PM: Info: LoadAddons: Tamagawa.EnmityPlugin.OverlayAddonMain: Initialized
2/14/2018 8:23:10 PM: Info: Enmity: The plugin is up to date. (v1.9.2.0)
2/14/2018 8:23:10 PM: Info: Enmity: Memory scanning started.
2/14/2018 8:23:11 PM: Info: Enmity: Attatched process successfully, pid: 23948 (dx11)
2/14/2018 8:23:11 PM: Info: InitPlugin: Initialized.
2/14/2018 8:23:11 PM: Error: Cactbot: Exception in SendFastRateEvents: Could not load file or assembly 'FFXIV_ACT_Plugin, Version=1.4.2.28, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
2/14/2018 8:23:11 PM: Error: Cactbot: Stack:    at Cactbot.CactbotOverlay.SendFastRateEvents()
   at Cactbot.CactbotOverlay.<.ctor>b__75_0(Object o, ElapsedEventArgs args)
2/14/2018 8:23:11 PM: Error: Cactbot: Source: CactbotOverlay
2/14/2018 8:23:11 PM: Error: Cactbot: Exception in SendFastRateEvents: Could not load file or assembly 'FFXIV_ACT_Plugin, Version=1.4.2.28, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
2/14/2018 8:23:11 PM: Error: Cactbot: Stack:    at Cactbot.CactbotOverlay.SendFastRateEvents()
   at Cactbot.CactbotOverlay.<.ctor>b__75_0(Object o, ElapsedEventArgs args)
2/14/2018 8:23:11 PM: Error: Cactbot: Source: CactbotOverlay
2/14/2018 8:23:11 PM: Error: RaidBoss: Exception in SendFastRateEvents: Could not load file or assembly 'FFXIV_ACT_Plugin, Version=1.4.2.28, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
2/14/2018 8:23:11 PM: Error: RaidBoss: Stack:    at Cactbot.CactbotOverlay.SendFastRateEvents()
   at Cactbot.CactbotOverlay.<.ctor>b__75_0(Object o, ElapsedEventArgs args)
2/14/2018 8:23:11 PM: Error: RaidBoss: Source: CactbotOverlay
2/14/2018 8:23:11 PM: Error: Cactbot: Exception in SendFastRateEvents: Could not load file or assembly 'FFXIV_ACT_Plugin, Version=1.4.2.28, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
2/14/2018 8:23:11 PM: Error: Cactbot: Stack:    at Cactbot.CactbotOverlay.SendFastRateEvents()
   at Cactbot.CactbotOverlay.<.ctor>b__75_0(Object o, ElapsedEventArgs args)
2/14/2018 8:23:11 PM: Error: Cactbot: Source: CactbotOverlay
2/14/2018 8:23:11 PM: Error: RaidBoss: Exception in SendFastRateEvents: Could not load file or assembly 'FFXIV_ACT_Plugin, Version=1.4.2.28, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
2/14/2018 8:23:11 PM: Error: RaidBoss: Stack:    at Cactbot.CactbotOverlay.SendFastRateEvents()
   at Cactbot.CactbotOverlay.<.ctor>b__75_0(Object o, ElapsedEventArgs args)
2/14/2018 8:23:11 PM: Error: RaidBoss: Source: CactbotOverlay
2/14/2018 8:23:11 PM: Error: Cactbot: Exception in SendFastRateEvents: Could not load file or assembly 'FFXIV_ACT_Plugin, Version=1.4.2.28, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
2/14/2018 8:23:11 PM: Error: Cactbot: Stack:    at Cactbot.CactbotOverlay.SendFastRateEvents()
   at Cactbot.CactbotOverlay.<.ctor>b__75_0(Object o, ElapsedEventArgs args)
2/14/2018 8:23:11 PM: Error: Cactbot: Source: CactbotOverlay
2/14/2018 8:23:11 PM: Error: RaidBoss: Exception in SendFastRateEvents: Could not load file or assembly 'FFXIV_ACT_Plugin, Version=1.4.2.28, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
2/14/2018 8:23:11 PM: Error: RaidBoss: Stack:    at Cactbot.CactbotOverlay.SendFastRateEvents()
   at Cactbot.CactbotOverlay.<.ctor>b__75_0(Object o, ElapsedEventArgs args)
2/14/2018 8:23:11 PM: Error: RaidBoss: Source: CactbotOverlay
2/14/2018 8:23:11 PM: Error: Cactbot: Exception in SendFastRateEvents: Could not load file or assembly 'FFXIV_ACT_Plugin, Version=1.4.2.28, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
2/14/2018 8:23:11 PM: Error: Cactbot: Stack:    at Cactbot.CactbotOverlay.SendFastRateEvents()
   at Cactbot.CactbotOverlay.<.ctor>b__75_0(Object o, ElapsedEventArgs args)
2/14/2018 8:23:11 PM: Error: Cactbot: Source: CactbotOverlay
```

**Comment by quisquous** [comment]
It is very surprising to me that raidboss would work with these errors.

Where are you loading the ffxiv plugin from in your ACT config? Is it in the same directory as the ACT executable?

**Comment by quisquous** [comment]
Could you try replacing your OverlayPlugin/addons/CactbotOverlay.dll with the DLL in this zip file:
[CactbotOverlay.zip](https://github.com/quisquous/cactbot/files/1737905/CactbotOverlay.zip)

1.4.2.28 is the version I was building against locally.  I'm not sure why that works for me but doesn't work for you, but I'm curious if this experiment solves your problem.

**Comment by TKDBB84** [comment]
Still getting the errors same errors in the console with that build, but plugin still seems to work as expected.

**Comment by quisquous** [comment]
With that build, do you get the exact same error, with that exact same version number?

**Comment by TKDBB84** [comment]
different version number: full log below

```
2/19/2018 11:24:57 PM: Info: InitPlugin: PluginDirectory = C:\Program Files (x86)\Advanced Combat Tracker
2/19/2018 11:24:57 PM: Info: LoadAddons: C:\Program Files (x86)\Advanced Combat Tracker\addons\CactbotOverlay.dll
2/19/2018 11:24:57 PM: Info: LoadAddons: Cactbot.OverlayAddonMain: Initialized
2/19/2018 11:24:57 PM: Info: LoadAddons: C:\Program Files (x86)\Advanced Combat Tracker\addons\EnmityOverlay.dll
2/19/2018 11:24:57 PM: Info: LoadAddons: Tamagawa.EnmityPlugin.OverlayAddonMain: Initialized
2/19/2018 11:24:58 PM: Info: Enmity: The plugin is up to date. (v1.9.3.0)
2/19/2018 11:24:58 PM: Info: Enmity: Memory scanning started.
2/19/2018 11:24:58 PM: Info: InitPlugin: Initialized.
2/19/2018 11:24:59 PM: Error: Cactbot: Exception in SendFastRateEvents: Could not load file or assembly 'FFXIV_ACT_Plugin, Version=1.6.2.5, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
2/19/2018 11:24:59 PM: Error: Cactbot: Stack:    at Cactbot.CactbotOverlay.SendFastRateEvents()
   at Cactbot.CactbotOverlay.<.ctor>b__75_0(Object o, ElapsedEventArgs args)
2/19/2018 11:24:59 PM: Error: Cactbot: Source: CactbotOverlay
2/19/2018 11:24:59 PM: Error: Cactbot: Exception in SendFastRateEvents: Could not load file or assembly 'FFXIV_ACT_Plugin, Version=1.6.2.5, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
2/19/2018 11:24:59 PM: Error: Cactbot: Stack:    at Cactbot.CactbotOverlay.SendFastRateEvents()
   at Cactbot.CactbotOverlay.<.ctor>b__75_0(Object o, ElapsedEventArgs args)
2/19/2018 11:24:59 PM: Error: Cactbot: Source: CactbotOverlay
2/19/2018 11:24:59 PM: Error: RaidBoss: Exception in SendFastRateEvents: Could not load file or assembly 'FFXIV_ACT_Plugin, Version=1.6.2.5, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
2/19/2018 11:24:59 PM: Error: RaidBoss: Stack:    at Cactbot.CactbotOverlay.SendFastRateEvents()
   at Cactbot.CactbotOverlay.<.ctor>b__75_0(Object o, ElapsedEventArgs args)
2/19/2018 11:24:59 PM: Error: RaidBoss: Source: CactbotOverlay
2/19/2018 11:24:59 PM: Error: Cactbot: Exception in SendFastRateEvents: Could not load file or assembly 'FFXIV_ACT_Plugin, Version=1.6.2.5, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
2/19/2018 11:24:59 PM: Error: Cactbot: Stack:    at Cactbot.CactbotOverlay.SendFastRateEvents()
   at Cactbot.CactbotOverlay.<.ctor>b__75_0(Object o, ElapsedEventArgs args)
2/19/2018 11:24:59 PM: Error: Cactbot: Source: CactbotOverlay
2/19/2018 11:24:59 PM: Error: RaidBoss: Exception in SendFastRateEvents: Could not load file or assembly 'FFXIV_ACT_Plugin, Version=1.6.2.5, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
2/19/2018 11:24:59 PM: Error: RaidBoss: Stack:    at Cactbot.CactbotOverlay.SendFastRateEvents()
   at Cactbot.CactbotOverlay.<.ctor>b__75_0(Object o, ElapsedEventArgs args)
2/19/2018 11:24:59 PM: Error: RaidBoss: Source: CactbotOverlay
```

**Comment by quisquous** [comment]
I'm sorry I haven't responded here in two weeks, but I've really been at a loss for how to fix this.

Just to confirm.
1. The FFXIV ACT plugin works properly (you get encounters, and dps results).
2. ACT itself is using the most recent FFXIV plugin 1.6.2.5, and you can confirm this in ACT by clicking on Plugins -> Plugin Lsiting -> FFXIV_ACT_Plugin.dll.
3. You don't have any other FFXIV_ACT_Plugin.dll files in your ACT folder or in your path, like in your Window system directory?
4. The cactbot test plugin works properly, in particular the zone name and the inCombat: act: true/false setting?

**Comment by TKDBB84** [comment]
That is all correct, it's not a big deal, the errors aren't causing any issue.  I just figured I'd report them just encase they revealed something to you about other possible bugs.  No worries!

**Comment by TKDBB84** [comment]
ooh based on your comment, I tried something:  I previously had iterated my FFXIV_ACT_Plugin just to keep older versions, so my FFXIV_ACT_Plugin.dll file was named:  `FFXIV_ACT_Plugin_4.dll`   when i renamed it to `FFXIV_ACT_Plugin.dll` errors were removed.  does ACT maybe provide a way to get the file name through it's API?

**Comment by quisquous** [comment]
Aha! Thanks for the investigation.  I think this is going to have to be the best solution.  I'm pretty sure you could maybe get the plugin names from ACT but it'd be tricky to know which was the right ffxiv plugin if it had been named something completely different.  So, in the end, no matter what, I think it comes down to having the right name.
