### ISSUE TITLE
Error on attempting to load cactbot: RainbowMage.OverlayPlugin.TinyIoCResolutionException: Unable to resolve type: Cactbot.CactbotEventSource...

### ISSUE THREAD

**Issue by darkk41** [quisquous/cactbot#765]
## Description

When I attempt to load the cactbot.dll in overlayPlugin's console window I get the following error:

[11/15/2019 3:47:03 PM] Error: LoadAddons: Cactbot.PluginLoader: RainbowMage.OverlayPlugin.TinyIoCResolutionException: Unable to resolve type: Cactbot.CactbotEventSource ---> RainbowMage.OverlayPlugin.TinyIoCResolutionException: Unable to resolve type: Cactbot.CactbotEventSource ---> System.MissingMethodException: Method not found: 'Void RainbowMage.OverlayPlugin.EventSourceBase.RegisterEventHandler(System.String, System.Func`2<Newtonsoft.Json.Linq.JObject,Newtonsoft.Json.Linq.JToken>)'.
   at Cactbot.CactbotEventSource..ctor(ILogger logger)
   at lambda_method(Closure , Object[] )
   at RainbowMage.OverlayPlugin.TinyIoCContainer.ConstructType(Type requestedType, Type implementationType, ConstructorInfo constructor, NamedParameterOverloads parameters, ResolveOptions options)
   --- End of inner exception stack trace ---
   at RainbowMage.OverlayPlugin.TinyIoCContainer.ConstructType(Type requestedType, Type implementationType, ConstructorInfo constructor, NamedParameterOverloads parameters, ResolveOptions options)
   at RainbowMage.OverlayPlugin.TinyIoCContainer.MultiInstanceFactory.GetObject(Type requestedType, TinyIoCContainer container, NamedParameterOverloads parameters, ResolveOptions options)
   --- End of inner exception stack trace ---
   at RainbowMage.OverlayPlugin.TinyIoCContainer.MultiInstanceFactory.GetObject(Type requestedType, TinyIoCContainer container, NamedParameterOverloads parameters, ResolveOptions options)
   at RainbowMage.OverlayPlugin.TinyIoCContainer.ResolveInternal(TypeRegistration registration, NamedParameterOverloads parameters, ResolveOptions options)
   at RainbowMage.OverlayPlugin.Registry.RegisterEventSource[T]()
   at RainbowMage.OverlayPlugin.PluginMain.LoadAddons()

I don't understand how to proceed. Currently using cactbot-0.12.2-ngdl, OverlayPlugin-0.10.1, ACT 64bit (a fresh installation). I have verified that I have .NET framework 4.8. I have also tried OverlayPlugin version 0.3.4.0 with similar results (slightly different error, also at load time and relating to RainbowMage) I have spent a few hours trying to get this working and am stumped. Am I running into a bug here or is there simply something I'm overlooking? Any help would be greatly appreciated.

Folder structure is 

ACT plugins
- OverlayPlugin/
- - OverlayPlugin.dll
- - cactbot/
- - - resources/
- - - ui/
- - - user/
- - addons/
- - - CactbotOverlay.dll

## Additional information

If available, please include any logs or screenshots depicting the issue you're experiencing.

**Comment by KattTails** [comment]
The ngld OverlayPlugin and cactbot does not require you to put the cactbot files into the OverlayPlugin folder. You should have it in it's own cactbot folder and load the OverlayPlugin.dll as an additional plugin in ACT.

**Comment by darkk41** [comment]
Thanks KattTails. So after following your suggestion it now loads without error, however I still do not see "Cactpot" as an available type in the "Type" dropdown of the overlay creator as shown in the 'About' section. Is this expected? Do i just create my Cactpot overlay as a MiniParse type or something instead?

**Comment by KattTails** [comment]
Please check the instructions [here](https://github.com/quisquous/cactbot/releases/tag/v0.11.1) and the linked instructions to ngld's page for how to set it up. This should all be explained there.

**Comment by darkk41** [comment]
I see, I was unaware of the ngld version specific instructions. Thanks for all the help! It is working now so I will close the ticket.
