### ISSUE TITLE
Trying to change to NGLD and getting errors

### ISSUE THREAD

**Issue by Smuggus** [quisquous/cactbot#781]
I followed the directions to convert from hibaya sleep to ngld plugin and whenever i attempt to load cactbot as a mini parse in my overlaydll tab i get this error:
Error: JS Handler call failed: System.Exception: Tried to call missing handler "cactbotLoadUser"!
   at RainbowMage.OverlayPlugin.EventDispatcher.CallHandler(JObject e)
   at RainbowMage.OverlayPlugin.OverlayApi.<>c__DisplayClass16_0.<callHandler>b__0()

I receive a wall of errors when attempting to reload a parser provided by cactbot. Am i able to continue using kagerou as a parser and convert cactbot to ngld? If so how do i set that up? I apologize as I am not tech savvy :C

**Comment by ngld** [comment]
Did you load `CactbotOverlay` as an ACT plugin? Does the Cactbot version appear in your overlay log?

**Comment by bondac** [comment]
I was seeing this same error - removed the old OverlayPlugin folder from inside my ACT folder and I'm not seeing the error anymore. Assume it was attempting to use the old cactbot code.

**Comment by osuka91** [comment]
now my spell timmer isn't working. are we supposed to reinstall all our other plugins?

**Comment by osuka91** [comment]
is the striking dummy in Summerford farms still used to test if the plugin is working?

**Comment by Smuggus** [comment]
Yes I loaded cactbot into the plugins, I believe I removed the overlay plug ins folder but I'll make sure I did

**Comment by MarkBerube** [comment]
Same error for on latest. I found that on latest install I still had Rainbow mage overlay/cactbot data in %appdata%/Advanced Combat Tracker/ and deleting it fixed it for me.

**Comment by Smuggus** [comment]
So i discovered that, somewhere along the way i had an old cactbot file inside of my ACT folder. I deleted it and now i have a working cactbot, thank you all for your help!

**Comment by haojunsui** [comment]
Similar error still existed. Switched to nlgd when Cactbot was 0.11.0, and no such error back then. Hence, not a old cactbot file problem in my case.

Log:

[2019/11/26 17:25:29] Info: InitPlugin: PluginDirectory = C:\Program Files (x86)\Advanced Combat Tracker\OverlayPlugin
[2019/11/26 17:25:30] Info: InitPlugin: Initialized.
[2019/11/26 17:25:31] Info: cactbot: 0.13.0.0 
[2019/11/26 17:25:31] Info: OverlayPlugin: 0.11.2.0 
[2019/11/26 17:25:31] Info: FFXIV Plugin: 2.0.4.5 C:\Users\suiha\AppData\Roaming\Advanced Combat Tracker\Plugins\FFXIV_ACT_Plugin.dll
[2019/11/26 17:25:31] Info: ACT: 3.4.5.265 C:\Program Files (x86)\Advanced Combat Tracker\Advanced Combat Tracker.exe
[2019/11/26 17:25:31] Info: Language: en
[2019/11/26 17:25:31] Info: LoadAddons: CactbotOverlay.dll: Initialized
[2019/11/26 17:25:32] Error: JS Handler call failed: System.Exception: Handler response must be an object or null at RainbowMage.OverlayPlugin.OverlayApi.<>c__DisplayClass16_0.<callHandler>b__0()

**Comment by MarkBerube** [comment]
@haojunsui 0.11.0 nlgd still worked with rainbow mage overlay data that hanged around in app data or program files - this one doesn't entirely. Go to `%appdata%/ACT/` and check for any files or dirs related to rainbow mage still and delete them.

**Comment by haojunsui** [comment]
error still shows even on a clean install on different machine, which has never installed ACT before.

**Comment by quisquous** [comment]
Is the handler error still occurring? I fixed something similar related to pull counter.  (Are you using the pull counter?)

**Comment by quisquous** [comment]
Let me know if this is still happening.  I think this was fixed along with the pull counter issue.  If not, let me know and we can keep trying to debug it.
