### ISSUE TITLE
Cactbot/Raidboss not connecting or detecting ffxiv

### ISSUE THREAD

**Issue by Snuwu** [quisquous/cactbot#835]
[12/6/2019 5:36:28 PM] Error: JS Handler call failed: System.Exception: Tried to call missing handler "cactbotLoadUser"!
   at RainbowMage.OverlayPlugin.EventDispatcher.CallHandler(JObject e)
   at RainbowMage.OverlayPlugin.OverlayApi.<>c__DisplayClass16_0.<callHandler>b__0()

ever since the ngld update all cactbot programs have had issues, i isolated it to this, and i must be missing something insanely small. The countdown test, bow test, and every other test arent starting raidboss either.

I also feel like the installation instructions should be updated along with the switch to ngld. without the .dll files being necessary to install, and new things being forced with this, these changes are pretty confusing to me and others im sure.

**Comment by Snuwu** [comment]
took the time to figure it out, it was confusing the user folders on my pc.
