### ISSUE TITLE
raidboss and jobs aren't working

### ISSUE THREAD

**Issue by fenrir262** [quisquous/cactbot#849]
[12/12/2019 6:02:48 PM] Error: JS Handler call failed: System.Exception: Tried to call missing handler "cactbotLoadUser"!
   at RainbowMage.OverlayPlugin.EventDispatcher.CallHandler(JObject e)
   at RainbowMage.OverlayPlugin.OverlayApi.<>c__DisplayClass16_0.<callHandler>b__0()
is the error I'm getting

**Comment by quisquous** [comment]
Hope you got this fixed!
