### ISSUE TITLE
Getting no response for Cactbot

### ISSUE THREAD

**Issue by illhatjr28** [quisquous/cactbot#938]
Apologies if this has already been answered, i recently came back to game to update cactbot and overlay and swapped over to new overlay. But now im having issues with getting cactbot to work. I have the cactbot downloaded and selected as a miniparse, and I pick the raidboss html but im just getting nothing once i lock and enable clickthrough. been doing hades ex and getting no timer and no callouts (i changed the raidboss file to allow text to speech). Is there a new way to activate text to speech and is my altered file causing an error to cactbot? or maybe im putting it in the wrong folder? Any help is appreciated. thanks again for your time.

**Comment by quisquous** [comment]
Are there any errors in your overlayplugin log?

**Comment by illhatjr28** [comment]
im getting an error i believe for enmity plugin, but I didnt think that was associated with cactbot

**Comment by illhatjr28** [comment]
when i reload overlay for raidboss im not getting anything in the log at all. not even that its loading

**Comment by illhatjr28** [comment]
oh i got an error after restarting ACT.

[1/7/2020 10:06:03 PM] Info: InitPlugin: PluginDirectory = E:\Advanced Combat Tracker\Overlay Plugin
[1/7/2020 10:06:03 PM] Info: InitPlugin: Initialized.
[1/7/2020 10:06:04 PM] Info: cactbot: 0.13.5.0 E:\cactbot-master\cactbot-0.13.4\cactbot\CactbotOverlay.dll (dir: E:\cactbot-master\cactbot-0.13.4\cactbot)
[1/7/2020 10:06:04 PM] Info: OverlayPlugin: 0.12.2.0 E:\Advanced Combat Tracker\Overlay Plugin\OverlayPlugin.dll
[1/7/2020 10:06:04 PM] Info: FFXIV Plugin: 2.0.4.13 E:\Advanced Combat Tracker\FFXIV_ACT_Plugin.dll
[1/7/2020 10:06:04 PM] Info: ACT: 3.4.5.266 E:\Advanced Combat Tracker\Advanced Combat Tracker.exe
[1/7/2020 10:06:04 PM] Info: Language: en
[1/7/2020 10:06:04 PM] Info: Version: intl
[1/7/2020 10:06:04 PM] Error: There is a new version of Cactbot is available at: 
https://github.com/quisquous/cactbot/releases/latest 

New version 0.14.1 
Current version 0.13.5.0
[1/7/2020 10:06:04 PM] Info: LoadAddons: CactbotOverlay.dll: Initialized
[1/7/2020 10:06:04 PM] Info: LoadAddons: E:\Advanced Combat Tracker\Overlay Plugin\addons\CactbotOverlay.dll
[1/7/2020 10:06:04 PM] Error: LoadAddons: Skipped CactbotOverlay, Version=0.12.1.0, Culture=neutral, PublicKeyToken=null because it's incompatible with this version of OverlayPlugin.
[1/7/2020 10:06:04 PM] Info: LoadAddons: E:\Advanced Combat Tracker\Overlay Plugin\addons\EnmityOverlay.dll
[1/7/2020 10:06:04 PM] Error: LoadAddons: Skipped EnmityOverlay, Version=1.10.0.0, Culture=neutral, PublicKeyToken=null because it's incompatible with this version of OverlayPlugin.

The problem is i went to update my Overlay plugin and it says I have the current version.

**Comment by illhatjr28** [comment]
Oh i didnt notice i didnt have the new updated version, i think it might be working now.

im getting the error:
[1/7/2020 10:09:31 PM] Error: Got a subscription for missing event "onForceReload"!

But i just tried a fight and the timeline is working now. not really sure what that error means. 

Going to test my file with text to speech to make sure that works as well.

**Comment by illhatjr28** [comment]
Bah now im getting a new string of errors, even after replacing the old raidboss.js

[1/7/2020 10:24:08 PM] Info: InitPlugin: PluginDirectory = E:\Advanced Combat Tracker\Overlay Plugin
[1/7/2020 10:24:08 PM] Info: InitPlugin: Initialized.
[1/7/2020 10:24:09 PM] Info: LoadAddons: E:\Advanced Combat Tracker\Overlay Plugin\addons\CactbotOverlay.dll
[1/7/2020 10:24:09 PM] Error: LoadAddons: Skipped CactbotOverlay, Version=0.12.1.0, Culture=neutral, PublicKeyToken=null because it's incompatible with this version of OverlayPlugin.
[1/7/2020 10:24:09 PM] Info: LoadAddons: E:\Advanced Combat Tracker\Overlay Plugin\addons\EnmityOverlay.dll
[1/7/2020 10:24:09 PM] Error: LoadAddons: Skipped EnmityOverlay, Version=1.10.0.0, Culture=neutral, PublicKeyToken=null because it's incompatible with this version of OverlayPlugin.
[1/7/2020 10:24:10 PM] Error: Got a subscription for missing event "onUserFileChanged"!
[1/7/2020 10:24:10 PM] Error: Got a subscription for missing event "onForceReload"!
[1/7/2020 10:24:10 PM] Error: JS Handler call failed: System.Exception: Tried to call missing handler "cactbotLoadData"!
   at RainbowMage.OverlayPlugin.EventDispatcher.CallHandler(JObject e)
   at RainbowMage.OverlayPlugin.EventDispatcher.ProcessHandlerMessage(IEventReceiver receiver, String data)
[1/7/2020 10:24:10 PM] Error: JS Handler call failed: System.Exception: Tried to call missing handler "cactbotLoadUser"!
   at RainbowMage.OverlayPlugin.EventDispatcher.CallHandler(JObject e)
   at RainbowMage.OverlayPlugin.EventDispatcher.ProcessHandlerMessage(IEventReceiver receiver, String data)
[1/7/2020 10:24:10 PM] Info: Raidboss: BrowserConsole: Uncaught (in promise) TypeError: Cannot read property 'detail' of null (Source: file:///E:/cactbot-master/cactbot-0.14.1/cactbot/resources/user_config.js, Line: 35)

I think im just making this worse ><;;

**Comment by ngld** [comment]
Please read the installation instructions again.
The `addons` folder should be empty and Cactbot has to be added as a plugin to ACT's `Plugins` tab.

**Comment by illhatjr28** [comment]
Oh your 100% correct I downloaded the updated version of cactbot but did not re add Cactbot as a plugin, also clearing the addon folder did the trick. Got my text to speech working as well. Thank you so much!

**Comment by illhatjr28** [comment]
ngld and quisquous are wonderful, got my issue solved super fast
