### ISSUE TITLE
user_config.js error?

### ISSUE THREAD

**Issue by mattarolla** [quisquous/cactbot#968]
[1/14/2020 5:14:54 PM] Info: InitPlugin: PluginDirectory = C:\Program Files\OverlayPlugin
[1/14/2020 5:14:54 PM] Info: InitPlugin: Initialized.
[1/14/2020 5:14:56 PM] Error: Got a subscription for missing event "onUserFileChanged"!
[1/14/2020 5:14:56 PM] Error: Got a subscription for missing event "onForceReload"!
[1/14/2020 5:14:56 PM] Error: JS Handler call failed: System.Exception: Tried to call missing handler "cactbotLoadData"!
   at RainbowMage.OverlayPlugin.EventDispatcher.CallHandler(JObject e)
   at RainbowMage.OverlayPlugin.EventDispatcher.ProcessHandlerMessage(IEventReceiver receiver, String data)
[1/14/2020 5:14:56 PM] Error: JS Handler call failed: System.Exception: Tried to call missing handler "cactbotLoadUser"!
   at RainbowMage.OverlayPlugin.EventDispatcher.CallHandler(JObject e)
   at RainbowMage.OverlayPlugin.EventDispatcher.ProcessHandlerMessage(IEventReceiver receiver, String data)
[1/14/2020 5:14:56 PM] Info: death: BrowserConsole: Uncaught (in promise) TypeError: Cannot read property 'detail' of null (Source: file:///C:/Program%20Files/OverlayPlugin/cactbot/resources/user_config.js, Line: 35)
[1/14/2020 5:14:56 PM] Error: Got a subscription for missing event "onUserFileChanged"!
[1/14/2020 5:14:56 PM] Error: Got a subscription for missing event "onForceReload"!
[1/14/2020 5:14:56 PM] Error: JS Handler call failed: System.Exception: Tried to call missing handler "cactbotLoadData"!
   at RainbowMage.OverlayPlugin.EventDispatcher.CallHandler(JObject e)
   at RainbowMage.OverlayPlugin.EventDispatcher.ProcessHandlerMessage(IEventReceiver receiver, String data)
[1/14/2020 5:14:56 PM] Error: JS Handler call failed: System.Exception: Tried to call missing handler "cactbotLoadUser"!
   at RainbowMage.OverlayPlugin.EventDispatcher.CallHandler(JObject e)
   at RainbowMage.OverlayPlugin.EventDispatcher.ProcessHandlerMessage(IEventReceiver receiver, String data)
[1/14/2020 5:14:56 PM] Info: raidboss: BrowserConsole: Uncaught (in promise) TypeError: Cannot read property 'detail' of null (Source: file:///C:/Program%20Files/OverlayPlugin/cactbot/resources/user_config.js, Line: 35)

**Comment by ngld** [comment]
Please enable `CactbotOverlay.dll` and restart ACT.

**Comment by mattarolla** [comment]
Sorry! I didn't realize it was disabled. Thank you.
