### ISSUE TITLE
Cactbot no longer shows and .dll error

### ISSUE THREAD

**Issue by chiasura** [quisquous/cactbot#996]
[1/26/2020 6:04:32 PM] Info: InitPlugin: PluginDirectory = D:\Advanced Combat Tracker Plugins\OverlayPlugin
[1/26/2020 6:04:33 PM] Info: InitPlugin: Initialized.
[1/26/2020 6:04:35 PM] Error: LoadAddons: CactbotOverlay.dll: System.InvalidCastException: Unable to cast object of type 'Cactbot.PluginLoader' to type 'RainbowMage.OverlayPlugin.IOverlayAddonV2'.
   at RainbowMage.OverlayPlugin.PluginMain.LoadAddons()
[1/26/2020 6:04:35 PM] Info: WS: Warn: The current logging level has been changed to Info. 

My cactbot overlay used to show up in the overlay addon. It's no longer there now. When creating a new overlay there are no cactbot presets. 

ACT Version 3.4.5
Cactbot 0.15.2
Overlay Plugin 0.13.0

**Comment by ngld** [comment]
Try updating OverlayPlugin. 0.13.2 is the latest version. If it doesn't ask automatically, go to Plugins > OverlayPlugin.dll > General > Check For Updates and let it update, then restart ACT.

**Comment by chiasura** [comment]
I didn't see a 0.13.2. Maybe I was clicking an old link... I helped a friend get cactbot and the new overlay working today on his computer, and his is giving him the same error. 

I personally uninstalled everything and reinstalled it and now its working. I will have my friend update his overlay plugin(even tho it did prompt him to update and he did and still had the error).

**Comment by Lokidoki8017** [comment]
I am getting same error 

Error: LoadAddons: CactbotOverlay.dll: System.InvalidCastException: Unable to cast object of type 'Cactbot.PluginLoader' to type 'RainbowMage.OverlayPlugin.IOverlayAddonV2'.
at RainbowMage.OverlayPlugin.PluginMain.LoadAddons()

OverlayPlugin up todate

**Comment by Lokidoki8017** [comment]
now getting this

[27/01/2020 22:14:19] Info: InitPlugin: PluginDirectory = E:\Advanced Combat Tracker\OverlayPlugin
[27/01/2020 22:14:19] Info: InitPlugin: Initialized.
[27/01/2020 22:14:20] Error: Got a subscription for missing event "onUserFileChanged"!
[27/01/2020 22:14:20] Error: Got a subscription for missing event "onForceReload"!
[27/01/2020 22:14:20] Error: JS Handler call failed: System.Exception: Tried to call missing handler "cactbotLoadData"!
   at RainbowMage.OverlayPlugin.EventDispatcher.CallHandler(JObject e)
   at RainbowMage.OverlayPlugin.EventDispatcher.ProcessHandlerMessage(IEventReceiver receiver, String data)
[27/01/2020 22:14:20] Error: JS Handler call failed: System.Exception: Tried to call missing handler "cactbotLoadUser"!
   at RainbowMage.OverlayPlugin.EventDispatcher.CallHandler(JObject e)
   at RainbowMage.OverlayPlugin.EventDispatcher.ProcessHandlerMessage(IEventReceiver receiver, String data)
[27/01/2020 22:14:20] Info: Raid: BrowserConsole: Uncaught (in promise) TypeError: Cannot read property 'detail' of null (Source: file:///E:/Advanced%20Combat%20Tracker/cactbot/resources/user_config.js, Line: 35)

**Comment by RhapsodySL** [comment]
I'm currently running into the same issue, running the latest version of ACT, ngld OverlayPlugin, and Cactbot.

`---------------------------
Fatal Error - Unhandled Exception
---------------------------
An unhandled exception has occurred.  ACT may close.
Press Ctrl-C to copy this MessageBox.

System.IO.FileNotFoundException - Could not load file or assembly 'FFXIV_ACT_Plugin.Common, Version=2.0.2.2, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
   at RainbowMage.OverlayPlugin.FFXIVRepository.GetCurrentFFXIVProcess()

   at RainbowMage.OverlayPlugin.OverlayZCorrector.EnsureOverlaysAreOverGame(Object _)

   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at System.Threading.TimerQueueTimer.CallCallback()

   at System.Threading.TimerQueueTimer.Fire()

   at System.Threading.TimerQueue.FireNextTimers()

RainbowMage.OverlayPlugin.FFXIVRepository, OverlayPlugin.Core, Version=0.13.2.0, Culture=neutral, PublicKeyToken=null
---------------------------
OK   
---------------------------
`

**Comment by ngld** [comment]
@RhapsodySL That's not the same issue... your FFXIV plugin is disabled.
@Lokidoki8017 Are you sure that `CactbotOverlay.dll` is enabled? According to those log messages, it's not being loaded.

**Comment by XboxSarynn** [comment]
I've been getting this on my wife's machine. My ACT+Cactbot is working fine. I tried redoing the installs of OverlayPlugin and Cactbot to the latest versions but its not helping.

`[2/13/2020 10:38:59 PM] Info: InitPlugin: PluginDirectory = C:\Program Files (x86)\Advanced Combat Tracker\ngld_OverlayPlugin
[2/13/2020 10:38:59 PM] Info: InitPlugin: Initialized.
[2/13/2020 10:39:01 PM] Error: LoadAddons: CactbotOverlay.dll: System.InvalidCastException: Unable to cast object of type 'Cactbot.PluginLoader' to type 'RainbowMage.OverlayPlugin.IOverlayAddonV2'.
   at RainbowMage.OverlayPlugin.PluginMain.LoadAddons()`

**Comment by quisquous** [comment]
@Sarynn-Bot do you have any errors in the ACT notifications that say that you have unknown files in your ACT folder? You should make sure that OverlayPlugin.dll is not in the base ACT folder

**Comment by quisquous** [comment]
No worries! Thanks for letting me know.  Is anybody else on this issue still having the same problem?

**Comment by quisquous** [comment]
Sounds like nobody is.  I'll close this.
